# Qwen3.5-27B QLoRA on an M5 Mac (MLX)

This notebook fine-tunes the 4-bit `mlx-community/Qwen3.5-27B-4bit` checkpoint for rubric grading on a 48 GB M5 Mac. It uses MLX/Metal instead of CUDA, masks the prompt so loss is calculated only on the assistant JSON answer, and verifies the Mac's unified-memory capacity.

Requirements: Apple Silicon, macOS 14 or newer, Python 3.11 or 3.12, at least 32 GB unified memory, roughly 25 GB free disk space, and `training_data.csv` beside this notebook. Close memory-heavy applications before training. The initial model download is approximately 16 GB.

Run the cells in order. Training is deliberately gated behind `RUN_TRAINING = False` so Run All cannot accidentally start a multi-hour job.

## 1. Install the native Apple Silicon stack

Use a native arm64 Python environment, not a Rosetta/x86 environment. Restart the kernel after this cell if Jupyter requests it.

In [1]:
%pip install -U "mlx-lm[train]>=0.30.7" pandas pyyaml transformers ipywidgets

Requirement already satisfied: mlx-lm>=0.30.7 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from mlx-lm[train]>=0.30.7) (0.31.3)
Requirement already satisfied: pandas in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (3.0.5)
Requirement already satisfied: pyyaml in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (6.0.3)
Requirement already satisfied: transformers in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (5.16.1)
Requirement already satisfied: ipywidgets in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (8.1.9)
Requirement already satisfied: mlx>=0.31.2 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from mlx-lm>=0.30.7->mlx-lm[train]>=0.30.7) (0.32.2)
Requirement already satisfied: numpy in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from mlx-lm>=0.30.7->mlx-lm[train]>=0.30.7) (2.5.2)
Requirement already satisfied: sentencepiece in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from mlx-lm>=0.30.7->mlx-lm[train]>=0.30.7) (0.2.2)
Requirement already satisfied: protobuf in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from mlx-lm>=0.30.7->mlx-lm[train]>=0.30.7) (7.36.1)
Requirement already satisfied: jinja2 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from mlx-lm>=0.30.7->mlx-lm[train]>=0.30.7) (3.1.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from transformers) (1.29.0)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from transformers) (26.3)
Requirement already satisfied: regex>=2025.10.22 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from transformers) (2026.7.19)
Requirement already satisfied: tokenizers<0.24.0,>=0.23.1 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from transformers) (0.23.1)
Requirement already satisfied: typer in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from transformers) (0.27.2)
Requirement already satisfied: safetensors>=0.8.0 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from transformers) (4.70.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.32.4)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.6.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.2 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.6.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.16.0)
Requirement already satisfied: anyio in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.14.2)
Requirement already satisfied: certifi in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.7.22)
Requirement already satisfied: httpcore==1.* in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.19)
Requirement already satisfied: h11>=0.16 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: comm>=0.1.3 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from ipywidgets) (9.17.0)
Requirement already satisfied: traitlets>=4.3.1 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from ipywidgets) (5.16.1)
Requirement already satisfied: widgetsnbextension~=4.0.16 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from ipywidgets) (4.0.16)
Requirement already satisfied: jupyterlab_widgets~=3.0.17 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from ipywidgets) (3.0.17)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from ipython>=6.1.0->ipywidgets) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.6 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from ipython>=6.1.0->ipywidgets) (0.2.2)
Requirement already satisfied: pexpect>4.6 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from ipython>=6.1.0->ipywidgets) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from ipython>=6.1.0->ipywidgets) (3.0.53)
Requirement already satisfied: psutil>=7 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from ipython>=6.1.0->ipywidgets) (7.2.2)
Requirement already satisfied: pygments>=2.14.0 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from ipython>=6.1.0->ipywidgets) (2.21.0)
Requirement already satisfied: stack_data>=0.6.0 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: wcwidth>=0.1.4 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.8.2)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from jedi>=0.18.2->ipython>=6.1.0->ipywidgets) (0.8.7)
Requirement already satisfied: mlx-metal==0.32.2 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from mlx>=0.31.2->mlx-lm>=0.30.7->mlx-lm[train]>=0.30.7) (0.32.2)
Requirement already satisfied: datasets in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from mlx-lm[train]>=0.30.7) (5.0.1)
Requirement already satisfied: ptyprocess>=0.5 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from pexpect>4.6->ipython>=6.1.0->ipywidgets) (0.7.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (3.0.2)
Requirement already satisfied: pure_eval in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (0.2.3)
Requirement already satisfied: pyarrow>=21.0.0 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from datasets->mlx-lm[train]>=0.30.7) (25.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from datasets->mlx-lm[train]>=0.30.7) (0.4.1)
Requirement already satisfied: requests>=2.32.2 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from datasets->mlx-lm[train]>=0.30.7) (2.34.2)
Requirement already satisfied: xxhash in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from datasets->mlx-lm[train]>=0.30.7) (4.0.1)
Requirement already satisfied: multiprocess<0.70.20 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from datasets->mlx-lm[train]>=0.30.7) (0.70.19)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from fsspec[http]<=2026.6.0,>=2023.1.0->datasets->mlx-lm[train]>=0.30.7) (3.14.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets->mlx-lm[train]>=0.30.7) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets->mlx-lm[train]>=0.30.7) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets->mlx-lm[train]>=0.30.7) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets->mlx-lm[train]>=0.30.7) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets->mlx-lm[train]>=0.30.7) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets->mlx-lm[train]>=0.30.7) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.6.0,>=2023.1.0->datasets->mlx-lm[train]>=0.30.7) (1.24.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from requests>=2.32.2->datasets->mlx-lm[train]>=0.30.7) (3.5.1)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from requests>=2.32.2->datasets->mlx-lm[train]>=0.30.7) (2.7.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from jinja2->mlx-lm>=0.30.7->mlx-lm[train]>=0.30.7) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from typer->transformers) (0.0.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: mdurl~=0.1 in /opt/anaconda3/envs/lora/lib/python3.14/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

## 2. Hardware check and memory-aware profile

The 27B checkpoint itself occupies about 16 GB. The profile changes only the number of final transformer layers receiving adapters and the LoRA rank; batch size remains one. Override values only after a successful short run.

In [2]:
import ast
import csv
import json
import math
import platform
import re
import subprocess
import sys
from pathlib import Path

import mlx.core as mx
import pandas as pd
import yaml

if platform.system() != "Darwin" or platform.machine() != "arm64":
    raise RuntimeError("This notebook must run in a native arm64 Python environment on Apple Silicon.")
if not mx.metal.is_available():
    raise RuntimeError("MLX cannot access Metal. Check the Python architecture and macOS installation.")

memory_bytes = int(subprocess.check_output(["sysctl", "-n", "hw.memsize"], text=True).strip())
MEMORY_GB = round(memory_bytes / 1024**3)

if MEMORY_GB < 32:
    raise MemoryError(
        f"Detected {MEMORY_GB} GB. Qwen3.5-27B QLoRA is not safe at this capacity. "
        "Use mlx-community/Qwen3.5-9B-4bit instead."
    )
elif MEMORY_GB < 48:
    PROFILE = {"name": "32 GB conservative", "num_layers": 4, "rank": 4, "grad_checkpoint": True}
elif MEMORY_GB < 64:
    PROFILE = {"name": "48 GB memory-safe", "num_layers": 8, "rank": 8, "grad_checkpoint": True}
elif MEMORY_GB < 96:
    PROFILE = {"name": "64 GB balanced", "num_layers": 12, "rank": 8, "grad_checkpoint": False}
else:
    PROFILE = {"name": "96+ GB quality", "num_layers": 16, "rank": 16, "grad_checkpoint": False}

print(f"Python: {sys.version.split()[0]} ({platform.machine()})")
print(f"MLX: {mx.__version__}; Metal available: {mx.metal.is_available()}")
print(f"Unified memory: {MEMORY_GB} GB")
print("Selected profile:", PROFILE)

Python: 3.14.7 (arm64)
MLX: 0.32.2; Metal available: True
Unified memory: 48 GB
Selected profile: {'name': '48 GB memory-safe', 'num_layers': 8, 'rank': 8, 'grad_checkpoint': True}

## 3. Experiment configuration

Three epochs are used for this 2,165-row dataset. MLX counts micro-batch iterations, so the iteration count is calculated after splitting and rounded up to finish the final gradient-accumulation update.

In [3]:
MODEL_ID = "mlx-community/Qwen3.5-27B-4bit"
DATASET_PATH = Path("./training_data.csv")
DATA_DIR = Path("./mlx-qwen35-27b-data")
OUTPUT_DIR = Path("./qwen35-27b-grading-mlx-lora")
CONFIG_PATH = Path("./qwen35-27b-m5-lora.yaml")

SEED = 42
NUM_EPOCHS = 3
MAX_SEQ_LENGTH = 448
BATCH_SIZE = 1
GRAD_ACCUMULATION_STEPS = 8
LEARNING_RATE = 1e-5
LORA_DROPOUT = 0.05

if not DATASET_PATH.exists():
    raise FileNotFoundError(f"Place training_data.csv at {DATASET_PATH.resolve()}")

## 4. Load and validate the grading data

In [4]:
df = pd.read_csv(DATASET_PATH)
required = ["question", "desired_answer", "student_answer", "criteria[]", "criteria_score[]"]
missing = [column for column in required if column not in df.columns]
if missing:
    raise ValueError(f"Missing required columns: {missing}")

def parse_array(value):
    """Parse JSON/Python lists and the dataset's unquoted bracket format."""
    if isinstance(value, list):
        return value
    if pd.isna(value):
        return []
    text = str(value).strip()
    for _ in range(2):
        try:
            parsed = json.loads(text)
        except json.JSONDecodeError:
            break
        if isinstance(parsed, list):
            return parsed
        if isinstance(parsed, str):
            text = parsed.strip()
            continue
        break
    try:
        parsed = ast.literal_eval(text)
        if isinstance(parsed, list):
            return parsed
        if isinstance(parsed, str):
            text = parsed.strip()
    except (ValueError, SyntaxError):
        pass
    if not (text.startswith("[") and text.endswith("]")):
        raise ValueError(f"Expected a bracketed list, got {value!r}")
    inner = text[1:-1].strip()
    if not inner:
        return []
    if re.search(r",(?=Answer\s)", inner):
        return [item.strip() for item in re.split(r",(?=Answer\s)", inner)]
    return [item.strip() for item in next(csv.reader([inner], skipinitialspace=True))]

def parse_criteria(value, expected_count):
    items = parse_array(value)
    if len(items) == expected_count:
        return items
    text = str(value).strip()
    for _ in range(2):
        try:
            decoded = json.loads(text)
        except json.JSONDecodeError:
            break
        if isinstance(decoded, str):
            text = decoded.strip()
        else:
            break
    inner = text[1:-1].strip() if text.startswith("[") and text.endswith("]") else text
    items = [inner] if expected_count == 1 else re.split(r",(?=Answer\s)", inner)
    items = [item.strip() for item in items]
    if len(items) != expected_count:
        raise ValueError(f"Parsed {len(items)} criteria but expected {expected_count}: {value!r}")
    return items

df["criteria_score"] = df["criteria_score[]"].apply(lambda v: [int(x) for x in parse_array(v)])
df["criteria"] = df.apply(lambda r: parse_criteria(r["criteria[]"], len(r["criteria_score"])), axis=1)

bad_rows = []
for index, row in df.iterrows():
    if not row["criteria"] or len(row["criteria"]) != len(row["criteria_score"]):
        bad_rows.append((index, "criterion/label length mismatch"))
    elif any(int(score) not in (0, 1) for score in row["criteria_score"]):
        bad_rows.append((index, "non-binary label"))
if bad_rows:
    raise ValueError(f"Invalid rows (first 10): {bad_rows[:10]}")
print(f"Validated {len(df):,} rows")
df[["criteria", "criteria_score"]].head()

Validated 2,165 rows

                                            criteria criteria_score
0  [Answer mentions simulating behaviour of porti...            [0]
1  [Answer mentions simulating behaviour of porti...            [1]
2  [Answer mentions simulating behaviour of porti...            [1]
3  [Answer mentions simulating behaviour of porti...            [1]
4  [Answer mentions simulating behaviour of porti...            [0]

## 5. Build assistant-only chat examples and leakage-safe deterministic splits

The final chat message is the completion. `mask_prompt: true` in the MLX configuration excludes the system and user tokens from loss. Grading totals and maximum scores never enter the prompt. Rows sharing an assignment/question ID stay in the same split so validation and test results measure generalization to unseen questions.

In [5]:
SYSTEM_PROMPT = """You are a strict grading assistant.

Evaluate whether a student's answer fulfills each grading criterion independently.
For every criterion, output 1 if it is fulfilled and 0 if it is not.
Return ONLY a valid JSON array containing exactly one 0 or 1 per criterion, in the original order.
Do not include explanations, markdown, or any text outside the JSON array."""

def make_example(row):
    criteria_text = "\n".join(f"{i + 1}. {criterion}" for i, criterion in enumerate(row["criteria"]))
    user_prompt = (
        f"Question:\n{row['question']}\n\n"
        f"Desired answer:\n{row['desired_answer']}\n\n"
        f"Student answer:\n{row['student_answer']}\n\n"
        f"Criteria:\n{criteria_text}"
    )
    target = json.dumps([int(x) for x in row["criteria_score"]], separators=(",", ":"))
    return {
        "messages": [
            {"role": "system", "content": [{"type": "text", "text": SYSTEM_PROMPT}]},
            {"role": "user", "content": [{"type": "text", "text": user_prompt}]},
            {"role": "assistant", "content": [{"type": "text", "text": target}]},
        ]
    }

examples = [make_example(row) for _, row in df.iterrows()]
group_ids = df["id"].drop_duplicates().sample(frac=1, random_state=SEED).tolist()
n_train_groups = int(len(group_ids) * 0.80)
n_valid_groups = int(len(group_ids) * 0.10)
split_group_ids = {
    "train": set(group_ids[:n_train_groups]),
    "valid": set(group_ids[n_train_groups:n_train_groups + n_valid_groups]),
    "test": set(group_ids[n_train_groups + n_valid_groups:]),
}
split_indices = {
    name: df.index[df["id"].isin(ids)].tolist()
    for name, ids in split_group_ids.items()
}
assert not (split_group_ids["train"] & split_group_ids["valid"] | split_group_ids["train"] & split_group_ids["test"] | split_group_ids["valid"] & split_group_ids["test"])
splits = {name: [make_example(df.loc[i]) for i in indices] for name, indices in split_indices.items()}
print({name: {"groups": len(split_group_ids[name]), "rows": len(rows)} for name, rows in splits.items()})
print(json.dumps(splits["train"][0], indent=2, ensure_ascii=False))

{'train': {'groups': 64, 'rows': 1711}, 'valid': {'groups': 8, 'rows': 217}, 'test': {'groups': 9, 'rows': 237}}
{
  "messages": [
    {
      "role": "system",
      "content": [
        {
          "type": "text",
          "text": "You are a strict grading assistant.\n\nEvaluate whether a student's answer fulfills each grading criterion independently.\nFor every criterion, output 1 if it is fulfilled and 0 if it is not.\nReturn ONLY a valid JSON array containing exactly one 0 or 1 per criterion, in the original order.\nDo not include explanations, markdown, or any text outside the JSON array."
        }
      ]
    },
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "Question:\nWhat is the role of a prototype program in problem solving?\n\nDesired answer:\nTo simulate the behaviour of portions of the desired software product.\n\nStudent answer:\nHigh risk problems are address in the prototype program to make sure that the program is feasible.  A prototype may also be used to show a company that the software can be possibly programmed.\n\nCriteria:\n1. Answer mentions simulating behaviour of portions of desired software"
        }
      ]
    },
    {
      "role": "assistant",
      "content": [
        {
          "type": "text",
          "text": "[0]"
        }
      ]
    }
  ]
}

In [6]:
DATA_DIR.mkdir(parents=True, exist_ok=True)
for split_name, rows in splits.items():
    path = DATA_DIR / f"{split_name}.jsonl"
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, ensure_ascii=False) + "\n")
    print(f"Wrote {len(rows):,} examples to {path}")

Wrote 1,711 examples to mlx-qwen35-27b-data/train.jsonl
Wrote 217 examples to mlx-qwen35-27b-data/valid.jsonl
Wrote 237 examples to mlx-qwen35-27b-data/test.jsonl

## 6. Verify sequence lengths

This downloads tokenizer files only. The cell fails rather than silently truncating training examples. If your CSV changes and the maximum exceeds 448, increase the cap cautiously because activation memory grows with sequence length.

In [7]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)

def formatted_token_count(example):
    kwargs = {"tokenize": True, "add_generation_prompt": False}
    try:
        ids = tokenizer.apply_chat_template(example["messages"], enable_thinking=False, **kwargs)
    except TypeError:
        ids = tokenizer.apply_chat_template(example["messages"], **kwargs)
    input_ids = ids["input_ids"] if hasattr(ids, "keys") else ids
    return len(input_ids)

lengths = [formatted_token_count(example) for example in examples]
print(pd.Series(lengths).describe(percentiles=[0.5, 0.9, 0.95, 0.99]))
if max(lengths) > MAX_SEQ_LENGTH:
    raise ValueError(
        f"Longest example is {max(lengths)} tokens, above MAX_SEQ_LENGTH={MAX_SEQ_LENGTH}. "
        "Increase the cap or shorten the examples; do not train with silent truncation."
    )
print("All examples fit. Longest sequence:", max(lengths))

count    2165.000000
mean      189.078060
std        29.016454
min       139.000000
50%       186.000000
90%       227.000000
95%       239.000000
99%       263.360000
max       387.000000
dtype: float64
All examples fit. Longest sequence: 387

## 7. Write the optimized MLX-LM configuration

Adapters target both Qwen3.5 attention families: Q/K/V/O projections in full-attention layers and QKV/Z/output projections in linear-attention layers. MLP adapters are omitted to control memory and training time.

In [8]:
train_micro_batches_per_epoch = math.ceil(len(splits["train"]) / BATCH_SIZE)
REQUESTED_ITERS = train_micro_batches_per_epoch * NUM_EPOCHS
# MLX-LM does not flush a partial gradient accumulation at the end.
TOTAL_ITERS = math.ceil(REQUESTED_ITERS / GRAD_ACCUMULATION_STEPS) * GRAD_ACCUMULATION_STEPS
TOTAL_OPTIMIZER_STEPS = TOTAL_ITERS // GRAD_ACCUMULATION_STEPS
WARMUP_UPDATES = max(2, math.ceil(TOTAL_OPTIMIZER_STEPS * 0.05))
# MLX schedules are zero-indexed and switch at warmup + 1.
WARMUP_STEPS = WARMUP_UPDATES - 1
DECAY_UPDATES = TOTAL_OPTIMIZER_STEPS - WARMUP_UPDATES
DECAY_STEPS = max(1, DECAY_UPDATES - 1)
def align_to_optimizer_update(iterations):
    return max(GRAD_ACCUMULATION_STEPS, round(iterations / GRAD_ACCUMULATION_STEPS) * GRAD_ACCUMULATION_STEPS)
STEPS_PER_EVAL = align_to_optimizer_update(max(50, train_micro_batches_per_epoch // 4))
SAVE_EVERY = align_to_optimizer_update(max(100, train_micro_batches_per_epoch // 2))

config = {
    "model": MODEL_ID,
    "train": True,
    "fine_tune_type": "lora",
    "optimizer": "adamw",
    "optimizer_config": {"adamw": {"weight_decay": 0.01}},
    "data": str(DATA_DIR),
    "seed": SEED,
    "num_layers": PROFILE["num_layers"],
    "batch_size": BATCH_SIZE,
    "grad_accumulation_steps": GRAD_ACCUMULATION_STEPS,
    "iters": TOTAL_ITERS,
    "val_batches": min(32, len(splits["valid"])),
    "learning_rate": LEARNING_RATE,
    "steps_per_report": 10,
    "steps_per_eval": STEPS_PER_EVAL,
    "save_every": SAVE_EVERY,
    "adapter_path": str(OUTPUT_DIR),
    "max_seq_length": MAX_SEQ_LENGTH,
    "grad_checkpoint": PROFILE["grad_checkpoint"],
    # Clear cached allocations every step for stability on a memory-tight Mac.
    "clear_cache_threshold": 0,
    "mask_prompt": True,
    "lora_parameters": {
        "keys": [
            "self_attn.q_proj", "self_attn.k_proj", "self_attn.v_proj", "self_attn.o_proj",
            "linear_attn.in_proj_qkv", "linear_attn.in_proj_z", "linear_attn.out_proj",
        ],
        "rank": PROFILE["rank"],
        # MLX applies scale directly; 2.0 is PEFT alpha/rank = 16/8.
        "scale": 2.0,
        "dropout": LORA_DROPOUT,
    },
    "lr_schedule": {
        "name": "cosine_decay",
        "warmup": WARMUP_STEPS,
        "warmup_init": 1e-7,
        "arguments": [LEARNING_RATE, DECAY_STEPS, 5e-7],
    },
}

CONFIG_PATH.write_text(yaml.safe_dump(config, sort_keys=False), encoding="utf-8")
print(CONFIG_PATH.read_text())
print(f"Effective batch size: {BATCH_SIZE * GRAD_ACCUMULATION_STEPS}")
print(f"Iterations: {TOTAL_ITERS:,} (~{TOTAL_ITERS / train_micro_batches_per_epoch:.3f} passes over training data)")
print(f"Optimizer updates: {TOTAL_OPTIMIZER_STEPS:,}; warmup updates: {WARMUP_UPDATES:,}")

model: mlx-community/Qwen3.5-27B-4bit
train: true
fine_tune_type: lora
optimizer: adamw
optimizer_config:
  adamw:
    weight_decay: 0.01
data: mlx-qwen35-27b-data
seed: 42
num_layers: 8
batch_size: 1
grad_accumulation_steps: 8
iters: 5136
val_batches: 32
learning_rate: 1.0e-05
steps_per_report: 10
steps_per_eval: 424
save_every: 856
adapter_path: qwen35-27b-grading-mlx-lora
max_seq_length: 448
grad_checkpoint: true
clear_cache_threshold: 0
mask_prompt: true
lora_parameters:
  keys:
  - self_attn.q_proj
  - self_attn.k_proj
  - self_attn.v_proj
  - self_attn.o_proj
  - linear_attn.in_proj_qkv
  - linear_attn.in_proj_z
  - linear_attn.out_proj
  rank: 8
  scale: 2.0
  dropout: 0.05
lr_schedule:
  name: cosine_decay
  warmup: 32
  warmup_init: 1.0e-07
  arguments:
  - 1.0e-05
  - 608
  - 5.0e-07

Effective batch size: 8
Iterations: 5,136 (~3.002 passes over training data)
Optimizer updates: 642; warmup updates: 33

## 8. Train

First set `RUN_TRAINING = True`. Keep the Mac connected to power and close large applications. The training command uses `caffeinate` to prevent idle system sleep. The model downloads on the first run. MLX saves periodic checkpoints in the adapter directory.

If Metal reports an out-of-memory error, reduce `num_layers` by half. If a long Qwen3.5 run reports a Metal resource-limit error, restart Python and resume from the latest saved `adapters.safetensors` by adding `resume_adapter_file` to the YAML configuration.

In [9]:
RUN_TRAINING = True  # Change to True when the configuration above looks correct.

command = ["caffeinate", "-dimsu", sys.executable, "-m", "mlx_lm", "lora", "--config", str(CONFIG_PATH)]
print("Command:", " ".join(command))
if RUN_TRAINING:
    subprocess.run(command, check=True)
else:
    print("Training not started. Set RUN_TRAINING=True and rerun this cell.")

Command: caffeinate -dimsu /opt/anaconda3/envs/lora/bin/python -m mlx_lm lora --config qwen35-27b-m5-lora.yaml
Loading configuration file qwen35-27b-m5-lora.yaml
Loading pretrained model

Fetching 13 files: 100%|██████████| 13/13 [00:00<00:00, 3585.35it/s]

Loading datasets
Training
Trainable parameters: 0.009% (2.474M/26895.994M)
Starting training..., iters: 5136

Calculating loss...: 100%|██████████| 32/32 [00:19<00:00,  1.61it/s]

Iter 1: Val loss 3.272, Val took 19.896s
Iter 10: Train loss 3.093, Learning Rate 1.000e-07, It/sec 0.185, Tokens/sec 1.889, Trained Tokens 102, Peak mem 22.158 GB
Iter 20: Train loss 3.414, Learning Rate 4.094e-07, It/sec 0.238, Tokens/sec 2.095, Trained Tokens 190, Peak mem 22.158 GB
Iter 30: Train loss 3.371, Learning Rate 7.188e-07, It/sec 0.288, Tokens/sec 2.595, Trained Tokens 280, Peak mem 22.158 GB
Iter 40: Train loss 3.110, Learning Rate 1.337e-06, It/sec 0.271, Tokens/sec 2.764, Trained Tokens 382, Peak mem 23.126 GB
Iter 50: Train loss 3.283, Learning Rate 1.647e-06, It/sec 0.317, Tokens/sec 2.979, Trained Tokens 476, Peak mem 23.126 GB
Iter 60: Train loss 3.282, Learning Rate 1.956e-06, It/sec 0.333, Tokens/sec 3.064, Trained Tokens 568, Peak mem 23.126 GB
Iter 70: Train loss 3.146, Learning Rate 2.266e-06, It/sec 0.326, Tokens/sec 3.200, Trained Tokens 666, Peak mem 23.126 GB
Iter 80: Train loss 3.358, Learning Rate 2.884e-06, It/sec 0.383, Tokens/sec 3.371, Trained Tokens 754, Peak mem 23.126 GB
Iter 90: Train loss 3.516, Learning Rate 3.194e-06, It/sec 0.382, Tokens/sec 3.211, Trained Tokens 838, Peak mem 23.126 GB
Iter 100: Train loss 3.152, Learning Rate 3.503e-06, It/sec 0.335, Tokens/sec 3.146, Trained Tokens 932, Peak mem 23.126 GB
Iter 110: Train loss 3.273, Learning Rate 3.813e-06, It/sec 0.353, Tokens/sec 3.178, Trained Tokens 1022, Peak mem 23.126 GB
Iter 120: Train loss 3.295, Learning Rate 4.431e-06, It/sec 0.348, Tokens/sec 3.066, Trained Tokens 1110, Peak mem 23.126 GB
Iter 130: Train loss 2.810, Learning Rate 4.741e-06, It/sec 0.283, Tokens/sec 2.769, Trained Tokens 1208, Peak mem 23.133 GB
Iter 140: Train loss 3.194, Learning Rate 5.050e-06, It/sec 0.356, Tokens/sec 2.922, Trained Tokens 1290, Peak mem 23.133 GB
Iter 150: Train loss 2.823, Learning Rate 5.359e-06, It/sec 0.338, Tokens/sec 3.041, Trained Tokens 1380, Peak mem 23.133 GB
Iter 160: Train loss 2.353, Learning Rate 5.978e-06, It/sec 0.275, Tokens/sec 2.802, Trained Tokens 1482, Peak mem 23.133 GB
Iter 170: Train loss 2.291, Learning Rate 6.287e-06, It/sec 0.302, Tokens/sec 2.843, Trained Tokens 1576, Peak mem 23.133 GB
Iter 180: Train loss 2.112, Learning Rate 6.597e-06, It/sec 0.344, Tokens/sec 3.094, Trained Tokens 1666, Peak mem 23.133 GB
Iter 190: Train loss 1.975, Learning Rate 6.906e-06, It/sec 0.337, Tokens/sec 2.896, Trained Tokens 1752, Peak mem 23.133 GB
Iter 200: Train loss 1.535, Learning Rate 7.525e-06, It/sec 0.332, Tokens/sec 3.055, Trained Tokens 1844, Peak mem 23.133 GB
Iter 210: Train loss 1.205, Learning Rate 7.834e-06, It/sec 0.369, Tokens/sec 3.101, Trained Tokens 1928, Peak mem 23.133 GB
Iter 220: Train loss 0.636, Learning Rate 8.144e-06, It/sec 0.343, Tokens/sec 3.228, Trained Tokens 2022, Peak mem 23.133 GB
Iter 230: Train loss 0.306, Learning Rate 8.453e-06, It/sec 0.364, Tokens/sec 3.057, Trained Tokens 2106, Peak mem 23.133 GB
Iter 240: Train loss 0.258, Learning Rate 9.072e-06, It/sec 0.359, Tokens/sec 3.157, Trained Tokens 2194, Peak mem 23.133 GB
Iter 250: Train loss 0.114, Learning Rate 9.381e-06, It/sec 0.277, Tokens/sec 2.662, Trained Tokens 2290, Peak mem 23.133 GB
Iter 260: Train loss 0.288, Learning Rate 9.691e-06, It/sec 0.349, Tokens/sec 3.209, Trained Tokens 2382, Peak mem 23.133 GB
Iter 270: Train loss 0.171, Learning Rate 1.000e-05, It/sec 0.251, Tokens/sec 2.256, Trained Tokens 2472, Peak mem 27.573 GB
Iter 280: Train loss 0.249, Learning Rate 1.000e-05, It/sec 0.316, Tokens/sec 3.163, Trained Tokens 2572, Peak mem 27.573 GB
Iter 290: Train loss 0.032, Learning Rate 1.000e-05, It/sec 0.366, Tokens/sec 3.290, Trained Tokens 2662, Peak mem 27.573 GB
Iter 300: Train loss 0.220, Learning Rate 9.999e-06, It/sec 0.327, Tokens/sec 3.071, Trained Tokens 2756, Peak mem 27.573 GB
Iter 310: Train loss 0.080, Learning Rate 9.999e-06, It/sec 0.347, Tokens/sec 3.330, Trained Tokens 2852, Peak mem 27.573 GB
Iter 320: Train loss 0.139, Learning Rate 9.998e-06, It/sec 0.259, Tokens/sec 2.277, Trained Tokens 2940, Peak mem 27.573 GB
Iter 330: Train loss 0.104, Learning Rate 9.997e-06, It/sec 0.319, Tokens/sec 2.935, Trained Tokens 3032, Peak mem 27.573 GB
Iter 340: Train loss 0.183, Learning Rate 9.996e-06, It/sec 0.324, Tokens/sec 3.042, Trained Tokens 3126, Peak mem 27.573 GB
Iter 350: Train loss 0.203, Learning Rate 9.995e-06, It/sec 0.321, Tokens/sec 3.020, Trained Tokens 3220, Peak mem 27.573 GB
Iter 360: Train loss 0.113, Learning Rate 9.992e-06, It/sec 0.338, Tokens/sec 2.974, Trained Tokens 3308, Peak mem 27.573 GB
Iter 370: Train loss 0.104, Learning Rate 9.991e-06, It/sec 0.324, Tokens/sec 3.050, Trained Tokens 3402, Peak mem 27.573 GB
Iter 380: Train loss 0.122, Learning Rate 9.989e-06, It/sec 0.329, Tokens/sec 3.492, Trained Tokens 3508, Peak mem 27.573 GB
Iter 390: Train loss 0.159, Learning Rate 9.988e-06, It/sec 0.341, Tokens/sec 3.139, Trained Tokens 3600, Peak mem 27.573 GB
Iter 400: Train loss 0.184, Learning Rate 9.984e-06, It/sec 0.338, Tokens/sec 3.249, Trained Tokens 3696, Peak mem 27.573 GB
Iter 410: Train loss 0.137, Learning Rate 9.982e-06, It/sec 0.315, Tokens/sec 3.214, Trained Tokens 3798, Peak mem 27.573 GB
Iter 420: Train loss 0.140, Learning Rate 9.979e-06, It/sec 0.326, Tokens/sec 3.062, Trained Tokens 3892, Peak mem 27.573 GB

Calculating loss...: 100%|██████████| 32/32 [00:19<00:00,  1.67it/s]

Iter 424: Val loss 0.125, Val took 19.202s
Iter 430: Train loss 0.167, Learning Rate 9.977e-06, It/sec 0.340, Tokens/sec 3.125, Trained Tokens 3984, Peak mem 27.573 GB
Iter 440: Train loss 0.120, Learning Rate 9.972e-06, It/sec 0.330, Tokens/sec 3.237, Trained Tokens 4082, Peak mem 27.573 GB
Iter 450: Train loss 0.106, Learning Rate 9.969e-06, It/sec 0.340, Tokens/sec 3.127, Trained Tokens 4174, Peak mem 27.573 GB
Iter 460: Train loss 0.126, Learning Rate 9.966e-06, It/sec 0.356, Tokens/sec 3.203, Trained Tokens 4264, Peak mem 27.573 GB
Iter 470: Train loss 0.123, Learning Rate 9.964e-06, It/sec 0.335, Tokens/sec 3.212, Trained Tokens 4360, Peak mem 27.573 GB
Iter 480: Train loss 0.144, Learning Rate 9.957e-06, It/sec 0.330, Tokens/sec 3.165, Trained Tokens 4456, Peak mem 27.573 GB
Iter 490: Train loss 0.133, Learning Rate 9.954e-06, It/sec 0.329, Tokens/sec 3.092, Trained Tokens 4550, Peak mem 27.573 GB
Iter 500: Train loss 0.111, Learning Rate 9.950e-06, It/sec 0.329, Tokens/sec 3.023, Trained Tokens 4642, Peak mem 27.573 GB
Iter 510: Train loss 0.137, Learning Rate 9.947e-06, It/sec 0.324, Tokens/sec 3.114, Trained Tokens 4738, Peak mem 27.573 GB
Iter 520: Train loss 0.069, Learning Rate 9.939e-06, It/sec 0.348, Tokens/sec 2.991, Trained Tokens 4824, Peak mem 27.573 GB
Iter 530: Train loss 0.171, Learning Rate 9.935e-06, It/sec 0.321, Tokens/sec 3.020, Trained Tokens 4918, Peak mem 27.573 GB
Iter 540: Train loss 0.120, Learning Rate 9.931e-06, It/sec 0.319, Tokens/sec 3.062, Trained Tokens 5014, Peak mem 27.573 GB
Iter 550: Train loss 0.006, Learning Rate 9.927e-06, It/sec 0.358, Tokens/sec 3.365, Trained Tokens 5108, Peak mem 27.573 GB
Iter 560: Train loss 0.101, Learning Rate 9.918e-06, It/sec 0.357, Tokens/sec 3.360, Trained Tokens 5202, Peak mem 27.573 GB
Iter 570: Train loss 0.282, Learning Rate 9.913e-06, It/sec 0.323, Tokens/sec 2.970, Trained Tokens 5294, Peak mem 27.573 GB
Iter 580: Train loss 0.104, Learning Rate 9.909e-06, It/sec 0.334, Tokens/sec 3.137, Trained Tokens 5388, Peak mem 27.573 GB
Iter 590: Train loss 0.199, Learning Rate 9.904e-06, It/sec 0.341, Tokens/sec 3.209, Trained Tokens 5482, Peak mem 27.573 GB
Iter 600: Train loss 0.257, Learning Rate 9.894e-06, It/sec 0.342, Tokens/sec 3.353, Trained Tokens 5580, Peak mem 27.573 GB
Iter 610: Train loss 0.130, Learning Rate 9.889e-06, It/sec 0.319, Tokens/sec 3.253, Trained Tokens 5682, Peak mem 27.573 GB
Iter 620: Train loss 0.022, Learning Rate 9.883e-06, It/sec 0.360, Tokens/sec 3.164, Trained Tokens 5770, Peak mem 27.573 GB
Iter 630: Train loss 0.108, Learning Rate 9.878e-06, It/sec 0.336, Tokens/sec 3.161, Trained Tokens 5864, Peak mem 27.573 GB
Iter 640: Train loss 0.243, Learning Rate 9.866e-06, It/sec 0.307, Tokens/sec 3.190, Trained Tokens 5968, Peak mem 27.573 GB
Iter 650: Train loss 0.105, Learning Rate 9.861e-06, It/sec 0.347, Tokens/sec 3.192, Trained Tokens 6060, Peak mem 27.573 GB
Iter 660: Train loss 0.044, Learning Rate 9.855e-06, It/sec 0.325, Tokens/sec 3.253, Trained Tokens 6160, Peak mem 27.573 GB
Iter 670: Train loss 0.123, Learning Rate 9.849e-06, It/sec 0.371, Tokens/sec 3.194, Trained Tokens 6246, Peak mem 27.573 GB
Iter 680: Train loss 0.147, Learning Rate 9.836e-06, It/sec 0.340, Tokens/sec 3.336, Trained Tokens 6344, Peak mem 27.573 GB
Iter 690: Train loss 0.083, Learning Rate 9.830e-06, It/sec 0.334, Tokens/sec 3.337, Trained Tokens 6444, Peak mem 27.573 GB
Iter 700: Train loss 0.068, Learning Rate 9.823e-06, It/sec 0.349, Tokens/sec 3.209, Trained Tokens 6536, Peak mem 27.573 GB
Iter 710: Train loss 0.083, Learning Rate 9.816e-06, It/sec 0.357, Tokens/sec 3.359, Trained Tokens 6630, Peak mem 27.573 GB
Iter 720: Train loss 0.056, Learning Rate 9.803e-06, It/sec 0.347, Tokens/sec 3.262, Trained Tokens 6724, Peak mem 27.573 GB
Iter 730: Train loss 0.018, Learning Rate 9.795e-06, It/sec 0.357, Tokens/sec 3.358, Trained Tokens 6818, Peak mem 27.573 GB
Iter 740: Train loss 0.109, Learning Rate 9.788e-06, It/sec 0.326, Tokens/sec 3.068, Trained Tokens 6912, Peak mem 27.573 GB
Iter 750: Train loss 0.294, Learning Rate 9.781e-06, It/sec 0.311, Tokens/sec 3.108, Trained Tokens 7012, Peak mem 27.573 GB
Iter 760: Train loss 0.127, Learning Rate 9.766e-06, It/sec 0.342, Tokens/sec 3.078, Trained Tokens 7102, Peak mem 27.573 GB
Iter 770: Train loss 0.084, Learning Rate 9.758e-06, It/sec 0.357, Tokens/sec 3.142, Trained Tokens 7190, Peak mem 27.573 GB
Iter 780: Train loss 0.154, Learning Rate 9.751e-06, It/sec 0.332, Tokens/sec 3.118, Trained Tokens 7284, Peak mem 27.573 GB
Iter 790: Train loss 0.114, Learning Rate 9.743e-06, It/sec 0.336, Tokens/sec 3.093, Trained Tokens 7376, Peak mem 27.573 GB
Iter 800: Train loss 0.123, Learning Rate 9.726e-06, It/sec 0.321, Tokens/sec 3.017, Trained Tokens 7470, Peak mem 27.573 GB
Iter 810: Train loss 0.078, Learning Rate 9.718e-06, It/sec 0.321, Tokens/sec 2.950, Trained Tokens 7562, Peak mem 27.573 GB
Iter 820: Train loss 0.067, Learning Rate 9.710e-06, It/sec 0.347, Tokens/sec 3.191, Trained Tokens 7654, Peak mem 27.573 GB
Iter 830: Train loss 0.103, Learning Rate 9.701e-06, It/sec 0.335, Tokens/sec 3.084, Trained Tokens 7746, Peak mem 27.573 GB
Iter 840: Train loss 0.080, Learning Rate 9.684e-06, It/sec 0.354, Tokens/sec 3.259, Trained Tokens 7838, Peak mem 27.573 GB

Calculating loss...: 100%|██████████| 32/32 [00:19<00:00,  1.66it/s]

Iter 848: Val loss 0.117, Val took 19.261s
Iter 850: Train loss 0.110, Learning Rate 9.675e-06, It/sec 0.326, Tokens/sec 3.190, Trained Tokens 7936, Peak mem 27.573 GB
Iter 856: Saved adapter weights to qwen35-27b-grading-mlx-lora/adapters.safetensors and qwen35-27b-grading-mlx-lora/0000856_adapters.safetensors.
Iter 860: Train loss 0.026, Learning Rate 9.666e-06, It/sec 0.349, Tokens/sec 3.347, Trained Tokens 8032, Peak mem 27.573 GB
Iter 870: Train loss 0.132, Learning Rate 9.657e-06, It/sec 0.345, Tokens/sec 3.246, Trained Tokens 8126, Peak mem 27.573 GB
Iter 880: Train loss 0.041, Learning Rate 9.638e-06, It/sec 0.347, Tokens/sec 3.260, Trained Tokens 8220, Peak mem 27.573 GB
Iter 890: Train loss 0.057, Learning Rate 9.629e-06, It/sec 0.341, Tokens/sec 3.136, Trained Tokens 8312, Peak mem 27.573 GB
Iter 900: Train loss 0.080, Learning Rate 9.619e-06, It/sec 0.320, Tokens/sec 3.327, Trained Tokens 8416, Peak mem 27.573 GB
Iter 910: Train loss 0.131, Learning Rate 9.610e-06, It/sec 0.282, Tokens/sec 2.651, Trained Tokens 8510, Peak mem 27.573 GB
Iter 920: Train loss 0.096, Learning Rate 9.590e-06, It/sec 0.239, Tokens/sec 2.294, Trained Tokens 8606, Peak mem 27.573 GB
Iter 930: Train loss 0.038, Learning Rate 9.580e-06, It/sec 0.321, Tokens/sec 3.020, Trained Tokens 8700, Peak mem 27.573 GB
Iter 940: Train loss 0.065, Learning Rate 9.570e-06, It/sec 0.322, Tokens/sec 3.347, Trained Tokens 8804, Peak mem 27.573 GB
Iter 950: Train loss 0.080, Learning Rate 9.560e-06, It/sec 0.335, Tokens/sec 3.012, Trained Tokens 8894, Peak mem 27.573 GB
Iter 960: Train loss 0.100, Learning Rate 9.539e-06, It/sec 0.334, Tokens/sec 3.002, Trained Tokens 8984, Peak mem 27.573 GB
Iter 970: Train loss 0.098, Learning Rate 9.528e-06, It/sec 0.332, Tokens/sec 3.059, Trained Tokens 9076, Peak mem 27.573 GB
Iter 980: Train loss 0.181, Learning Rate 9.517e-06, It/sec 0.356, Tokens/sec 3.272, Trained Tokens 9168, Peak mem 27.573 GB
Iter 990: Train loss 0.105, Learning Rate 9.507e-06, It/sec 0.369, Tokens/sec 3.399, Trained Tokens 9260, Peak mem 27.573 GB
Iter 1000: Train loss 0.122, Learning Rate 9.485e-06, It/sec 0.343, Tokens/sec 3.358, Trained Tokens 9358, Peak mem 27.573 GB
Iter 1010: Train loss 0.048, Learning Rate 9.473e-06, It/sec 0.345, Tokens/sec 3.310, Trained Tokens 9454, Peak mem 27.573 GB
Iter 1020: Train loss 0.113, Learning Rate 9.462e-06, It/sec 0.328, Tokens/sec 3.144, Trained Tokens 9550, Peak mem 27.573 GB
Iter 1030: Train loss 0.085, Learning Rate 9.451e-06, It/sec 0.340, Tokens/sec 3.058, Trained Tokens 9640, Peak mem 27.573 GB
Iter 1040: Train loss 0.048, Learning Rate 9.428e-06, It/sec 0.339, Tokens/sec 3.049, Trained Tokens 9730, Peak mem 27.573 GB
Iter 1050: Train loss 0.070, Learning Rate 9.416e-06, It/sec 0.355, Tokens/sec 3.198, Trained Tokens 9820, Peak mem 27.573 GB
Iter 1060: Train loss 0.011, Learning Rate 9.404e-06, It/sec 0.334, Tokens/sec 3.140, Trained Tokens 9914, Peak mem 27.573 GB
Iter 1070: Train loss 0.161, Learning Rate 9.392e-06, It/sec 0.314, Tokens/sec 3.077, Trained Tokens 10012, Peak mem 27.573 GB
Iter 1080: Train loss 0.092, Learning Rate 9.368e-06, It/sec 0.346, Tokens/sec 3.248, Trained Tokens 10106, Peak mem 27.573 GB
Iter 1090: Train loss 0.076, Learning Rate 9.355e-06, It/sec 0.344, Tokens/sec 2.960, Trained Tokens 10192, Peak mem 27.573 GB
Iter 1100: Train loss 0.060, Learning Rate 9.343e-06, It/sec 0.360, Tokens/sec 3.165, Trained Tokens 10280, Peak mem 27.573 GB
Iter 1110: Train loss 0.039, Learning Rate 9.331e-06, It/sec 0.332, Tokens/sec 3.320, Trained Tokens 10380, Peak mem 27.573 GB
Iter 1120: Train loss 0.120, Learning Rate 9.305e-06, It/sec 0.335, Tokens/sec 3.012, Trained Tokens 10470, Peak mem 27.573 GB
Iter 1130: Train loss 0.082, Learning Rate 9.292e-06, It/sec 0.309, Tokens/sec 2.900, Trained Tokens 10564, Peak mem 27.573 GB
Iter 1140: Train loss 0.137, Learning Rate 9.279e-06, It/sec 0.334, Tokens/sec 3.139, Trained Tokens 10658, Peak mem 27.573 GB
Iter 1150: Train loss 0.066, Learning Rate 9.266e-06, It/sec 0.345, Tokens/sec 3.169, Trained Tokens 10750, Peak mem 27.573 GB
Iter 1160: Train loss 0.034, Learning Rate 9.240e-06, It/sec 0.350, Tokens/sec 3.217, Trained Tokens 10842, Peak mem 27.573 GB
Iter 1170: Train loss 0.008, Learning Rate 9.227e-06, It/sec 0.344, Tokens/sec 2.892, Trained Tokens 10926, Peak mem 27.573 GB
Iter 1180: Train loss 0.037, Learning Rate 9.213e-06, It/sec 0.352, Tokens/sec 3.308, Trained Tokens 11020, Peak mem 27.573 GB
Iter 1190: Train loss 0.108, Learning Rate 9.199e-06, It/sec 0.329, Tokens/sec 3.028, Trained Tokens 11112, Peak mem 27.573 GB
Iter 1200: Train loss 0.095, Learning Rate 9.172e-06, It/sec 0.334, Tokens/sec 3.072, Trained Tokens 11204, Peak mem 27.573 GB
Iter 1210: Train loss 0.048, Learning Rate 9.158e-06, It/sec 0.346, Tokens/sec 3.047, Trained Tokens 11292, Peak mem 27.573 GB
Iter 1220: Train loss 0.104, Learning Rate 9.144e-06, It/sec 0.347, Tokens/sec 3.264, Trained Tokens 11386, Peak mem 27.573 GB
Iter 1230: Train loss 0.047, Learning Rate 9.130e-06, It/sec 0.361, Tokens/sec 3.320, Trained Tokens 11478, Peak mem 27.573 GB
Iter 1240: Train loss 0.074, Learning Rate 9.101e-06, It/sec 0.343, Tokens/sec 3.227, Trained Tokens 11572, Peak mem 27.573 GB
Iter 1250: Train loss 0.154, Learning Rate 9.087e-06, It/sec 0.256, Tokens/sec 2.505, Trained Tokens 11670, Peak mem 27.573 GB
Iter 1260: Train loss 0.053, Learning Rate 9.073e-06, It/sec 0.312, Tokens/sec 2.999, Trained Tokens 11766, Peak mem 27.573 GB
Iter 1270: Train loss 0.073, Learning Rate 9.058e-06, It/sec 0.322, Tokens/sec 3.283, Trained Tokens 11868, Peak mem 27.573 GB

Calculating loss...: 100%|██████████| 32/32 [00:19<00:00,  1.64it/s]

Iter 1272: Val loss 0.062, Val took 19.526s
Iter 1280: Train loss 0.049, Learning Rate 9.028e-06, It/sec 0.365, Tokens/sec 2.990, Trained Tokens 11950, Peak mem 27.573 GB
Iter 1290: Train loss 0.078, Learning Rate 9.013e-06, It/sec 0.340, Tokens/sec 3.059, Trained Tokens 12040, Peak mem 27.573 GB
Iter 1300: Train loss 0.050, Learning Rate 8.998e-06, It/sec 0.343, Tokens/sec 3.290, Trained Tokens 12136, Peak mem 27.573 GB
Iter 1310: Train loss 0.026, Learning Rate 8.983e-06, It/sec 0.339, Tokens/sec 3.190, Trained Tokens 12230, Peak mem 27.573 GB
Iter 1320: Train loss 0.126, Learning Rate 8.953e-06, It/sec 0.376, Tokens/sec 3.162, Trained Tokens 12314, Peak mem 27.573 GB
Iter 1330: Train loss 0.079, Learning Rate 8.937e-06, It/sec 0.318, Tokens/sec 3.175, Trained Tokens 12414, Peak mem 27.573 GB
Iter 1340: Train loss 0.107, Learning Rate 8.922e-06, It/sec 0.351, Tokens/sec 3.091, Trained Tokens 12502, Peak mem 27.573 GB
Iter 1350: Train loss 0.051, Learning Rate 8.906e-06, It/sec 0.308, Tokens/sec 2.898, Trained Tokens 12596, Peak mem 27.573 GB
Iter 1360: Train loss 0.043, Learning Rate 8.875e-06, It/sec 0.339, Tokens/sec 3.117, Trained Tokens 12688, Peak mem 27.573 GB
Iter 1370: Train loss 0.047, Learning Rate 8.859e-06, It/sec 0.349, Tokens/sec 3.143, Trained Tokens 12778, Peak mem 27.573 GB
Iter 1380: Train loss 0.109, Learning Rate 8.843e-06, It/sec 0.258, Tokens/sec 2.687, Trained Tokens 12882, Peak mem 27.573 GB
Iter 1390: Train loss 0.051, Learning Rate 8.827e-06, It/sec 0.340, Tokens/sec 3.125, Trained Tokens 12974, Peak mem 27.573 GB
Iter 1400: Train loss 0.054, Learning Rate 8.794e-06, It/sec 0.335, Tokens/sec 3.422, Trained Tokens 13076, Peak mem 27.573 GB
Iter 1410: Train loss 0.047, Learning Rate 8.778e-06, It/sec 0.324, Tokens/sec 3.110, Trained Tokens 13172, Peak mem 27.573 GB
Iter 1420: Train loss 0.061, Learning Rate 8.761e-06, It/sec 0.319, Tokens/sec 3.253, Trained Tokens 13274, Peak mem 27.573 GB
Iter 1430: Train loss 0.069, Learning Rate 8.745e-06, It/sec 0.278, Tokens/sec 2.611, Trained Tokens 13368, Peak mem 27.573 GB
Iter 1440: Train loss 0.094, Learning Rate 8.711e-06, It/sec 0.347, Tokens/sec 3.195, Trained Tokens 13460, Peak mem 27.573 GB
Iter 1450: Train loss 0.040, Learning Rate 8.694e-06, It/sec 0.342, Tokens/sec 3.013, Trained Tokens 13548, Peak mem 27.573 GB
Iter 1460: Train loss 0.041, Learning Rate 8.677e-06, It/sec 0.331, Tokens/sec 3.046, Trained Tokens 13640, Peak mem 27.573 GB
Iter 1470: Train loss 0.129, Learning Rate 8.660e-06, It/sec 0.338, Tokens/sec 3.313, Trained Tokens 13738, Peak mem 27.573 GB
Iter 1480: Train loss 0.056, Learning Rate 8.626e-06, It/sec 0.350, Tokens/sec 3.148, Trained Tokens 13828, Peak mem 27.573 GB
Iter 1490: Train loss 0.077, Learning Rate 8.609e-06, It/sec 0.322, Tokens/sec 3.091, Trained Tokens 13924, Peak mem 27.573 GB
Iter 1500: Train loss 0.110, Learning Rate 8.591e-06, It/sec 0.370, Tokens/sec 3.400, Trained Tokens 14016, Peak mem 27.573 GB
Iter 1510: Train loss 0.068, Learning Rate 8.574e-06, It/sec 0.370, Tokens/sec 3.475, Trained Tokens 14110, Peak mem 27.573 GB
Iter 1520: Train loss 0.128, Learning Rate 8.539e-06, It/sec 0.358, Tokens/sec 3.146, Trained Tokens 14198, Peak mem 27.573 GB
Iter 1530: Train loss 0.065, Learning Rate 8.521e-06, It/sec 0.338, Tokens/sec 3.312, Trained Tokens 14296, Peak mem 27.573 GB
Iter 1540: Train loss 0.061, Learning Rate 8.503e-06, It/sec 0.335, Tokens/sec 3.218, Trained Tokens 14392, Peak mem 27.573 GB
Iter 1550: Train loss 0.074, Learning Rate 8.485e-06, It/sec 0.370, Tokens/sec 3.260, Trained Tokens 14480, Peak mem 27.573 GB
Iter 1560: Train loss 0.050, Learning Rate 8.449e-06, It/sec 0.342, Tokens/sec 3.422, Trained Tokens 14580, Peak mem 27.573 GB
Iter 1570: Train loss 0.064, Learning Rate 8.431e-06, It/sec 0.336, Tokens/sec 3.364, Trained Tokens 14680, Peak mem 27.573 GB
Iter 1580: Train loss 0.104, Learning Rate 8.413e-06, It/sec 0.335, Tokens/sec 3.288, Trained Tokens 14778, Peak mem 27.573 GB
Iter 1590: Train loss 0.031, Learning Rate 8.394e-06, It/sec 0.334, Tokens/sec 3.204, Trained Tokens 14874, Peak mem 27.573 GB
Iter 1600: Train loss 0.060, Learning Rate 8.357e-06, It/sec 0.316, Tokens/sec 2.911, Trained Tokens 14966, Peak mem 27.573 GB
Iter 1610: Train loss 0.061, Learning Rate 8.339e-06, It/sec 0.341, Tokens/sec 3.543, Trained Tokens 15070, Peak mem 27.573 GB
Iter 1620: Train loss 0.078, Learning Rate 8.320e-06, It/sec 0.348, Tokens/sec 3.200, Trained Tokens 15162, Peak mem 27.573 GB
Iter 1630: Train loss 0.043, Learning Rate 8.301e-06, It/sec 0.376, Tokens/sec 3.535, Trained Tokens 15256, Peak mem 27.573 GB
Iter 1640: Train loss 0.090, Learning Rate 8.263e-06, It/sec 0.349, Tokens/sec 3.215, Trained Tokens 15348, Peak mem 27.573 GB
Iter 1650: Train loss 0.045, Learning Rate 8.244e-06, It/sec 0.359, Tokens/sec 3.231, Trained Tokens 15438, Peak mem 27.573 GB
Iter 1660: Train loss 0.081, Learning Rate 8.225e-06, It/sec 0.343, Tokens/sec 3.084, Trained Tokens 15528, Peak mem 27.573 GB
Iter 1670: Train loss 0.111, Learning Rate 8.206e-06, It/sec 0.333, Tokens/sec 2.998, Trained Tokens 15618, Peak mem 27.573 GB
Iter 1680: Train loss 0.161, Learning Rate 8.168e-06, It/sec 0.339, Tokens/sec 3.118, Trained Tokens 15710, Peak mem 27.573 GB
Iter 1690: Train loss 0.108, Learning Rate 8.148e-06, It/sec 0.341, Tokens/sec 3.347, Trained Tokens 15808, Peak mem 27.573 GB

Calculating loss...: 100%|██████████| 32/32 [00:18<00:00,  1.69it/s]

Iter 1696: Val loss 0.053, Val took 18.944s
Iter 1700: Train loss 0.068, Learning Rate 8.129e-06, It/sec 0.360, Tokens/sec 3.455, Trained Tokens 15904, Peak mem 27.573 GB
Iter 1710: Train loss 0.116, Learning Rate 8.109e-06, It/sec 0.338, Tokens/sec 3.181, Trained Tokens 15998, Peak mem 27.573 GB
Iter 1712: Saved adapter weights to qwen35-27b-grading-mlx-lora/adapters.safetensors and qwen35-27b-grading-mlx-lora/0001712_adapters.safetensors.
Iter 1720: Train loss 0.095, Learning Rate 8.070e-06, It/sec 0.318, Tokens/sec 3.311, Trained Tokens 16102, Peak mem 27.573 GB
Iter 1730: Train loss 0.072, Learning Rate 8.050e-06, It/sec 0.332, Tokens/sec 3.190, Trained Tokens 16198, Peak mem 27.573 GB
Iter 1740: Train loss 0.077, Learning Rate 8.030e-06, It/sec 0.337, Tokens/sec 3.231, Trained Tokens 16294, Peak mem 27.573 GB
Iter 1750: Train loss 0.102, Learning Rate 8.010e-06, It/sec 0.343, Tokens/sec 3.085, Trained Tokens 16384, Peak mem 27.573 GB
Iter 1760: Train loss 0.072, Learning Rate 7.970e-06, It/sec 0.358, Tokens/sec 3.221, Trained Tokens 16474, Peak mem 27.573 GB
Iter 1770: Train loss 0.090, Learning Rate 7.950e-06, It/sec 0.359, Tokens/sec 3.521, Trained Tokens 16572, Peak mem 27.573 GB
Iter 1780: Train loss 0.024, Learning Rate 7.930e-06, It/sec 0.331, Tokens/sec 3.175, Trained Tokens 16668, Peak mem 27.573 GB
Iter 1790: Train loss 0.035, Learning Rate 7.909e-06, It/sec 0.367, Tokens/sec 3.447, Trained Tokens 16762, Peak mem 27.573 GB
Iter 1800: Train loss 0.043, Learning Rate 7.869e-06, It/sec 0.350, Tokens/sec 3.224, Trained Tokens 16854, Peak mem 27.573 GB
Iter 1810: Train loss 0.083, Learning Rate 7.848e-06, It/sec 0.345, Tokens/sec 3.103, Trained Tokens 16944, Peak mem 27.573 GB
Iter 1820: Train loss 0.082, Learning Rate 7.827e-06, It/sec 0.359, Tokens/sec 3.227, Trained Tokens 17034, Peak mem 27.573 GB
Iter 1830: Train loss 0.050, Learning Rate 7.807e-06, It/sec 0.359, Tokens/sec 3.228, Trained Tokens 17124, Peak mem 27.573 GB
Iter 1840: Train loss 0.029, Learning Rate 7.765e-06, It/sec 0.377, Tokens/sec 3.163, Trained Tokens 17208, Peak mem 27.573 GB
Iter 1850: Train loss 0.119, Learning Rate 7.744e-06, It/sec 0.348, Tokens/sec 3.409, Trained Tokens 17306, Peak mem 27.573 GB
Iter 1860: Train loss 0.107, Learning Rate 7.723e-06, It/sec 0.323, Tokens/sec 3.037, Trained Tokens 17400, Peak mem 27.573 GB
Iter 1870: Train loss 0.071, Learning Rate 7.703e-06, It/sec 0.326, Tokens/sec 3.133, Trained Tokens 17496, Peak mem 27.573 GB
Iter 1880: Train loss 0.113, Learning Rate 7.660e-06, It/sec 0.288, Tokens/sec 2.933, Trained Tokens 17598, Peak mem 27.583 GB
Iter 1890: Train loss 0.075, Learning Rate 7.639e-06, It/sec 0.344, Tokens/sec 3.436, Trained Tokens 17698, Peak mem 27.583 GB
Iter 1900: Train loss 0.060, Learning Rate 7.618e-06, It/sec 0.340, Tokens/sec 3.263, Trained Tokens 17794, Peak mem 27.583 GB
Iter 1910: Train loss 0.074, Learning Rate 7.597e-06, It/sec 0.365, Tokens/sec 3.284, Trained Tokens 17884, Peak mem 27.583 GB
Iter 1920: Train loss 0.051, Learning Rate 7.554e-06, It/sec 0.362, Tokens/sec 3.255, Trained Tokens 17974, Peak mem 27.583 GB
Iter 1930: Train loss 0.032, Learning Rate 7.532e-06, It/sec 0.371, Tokens/sec 3.336, Trained Tokens 18064, Peak mem 27.583 GB
Iter 1940: Train loss 0.068, Learning Rate 7.511e-06, It/sec 0.341, Tokens/sec 3.141, Trained Tokens 18156, Peak mem 27.583 GB
Iter 1950: Train loss 0.090, Learning Rate 7.489e-06, It/sec 0.348, Tokens/sec 3.477, Trained Tokens 18256, Peak mem 27.583 GB
Iter 1960: Train loss 0.101, Learning Rate 7.446e-06, It/sec 0.329, Tokens/sec 3.155, Trained Tokens 18352, Peak mem 27.583 GB
Iter 1970: Train loss 0.108, Learning Rate 7.424e-06, It/sec 0.344, Tokens/sec 3.232, Trained Tokens 18446, Peak mem 27.583 GB
Iter 1980: Train loss 0.085, Learning Rate 7.402e-06, It/sec 0.317, Tokens/sec 3.103, Trained Tokens 18544, Peak mem 27.583 GB
Iter 1990: Train loss 0.078, Learning Rate 7.380e-06, It/sec 0.349, Tokens/sec 3.214, Trained Tokens 18636, Peak mem 27.583 GB
Iter 2000: Train loss 0.055, Learning Rate 7.336e-06, It/sec 0.343, Tokens/sec 3.293, Trained Tokens 18732, Peak mem 27.583 GB
Iter 2010: Train loss 0.097, Learning Rate 7.314e-06, It/sec 0.335, Tokens/sec 3.146, Trained Tokens 18826, Peak mem 27.583 GB
Iter 2020: Train loss 0.052, Learning Rate 7.292e-06, It/sec 0.298, Tokens/sec 3.037, Trained Tokens 18928, Peak mem 27.583 GB
Iter 2030: Train loss 0.061, Learning Rate 7.270e-06, It/sec 0.347, Tokens/sec 2.988, Trained Tokens 19014, Peak mem 27.583 GB
Iter 2040: Train loss 0.059, Learning Rate 7.225e-06, It/sec 0.325, Tokens/sec 3.383, Trained Tokens 19118, Peak mem 27.583 GB
Iter 2050: Train loss 0.094, Learning Rate 7.203e-06, It/sec 0.348, Tokens/sec 3.130, Trained Tokens 19208, Peak mem 27.583 GB
Iter 2060: Train loss 0.066, Learning Rate 7.181e-06, It/sec 0.333, Tokens/sec 3.132, Trained Tokens 19302, Peak mem 27.583 GB
Iter 2070: Train loss 0.080, Learning Rate 7.158e-06, It/sec 0.326, Tokens/sec 3.066, Trained Tokens 19396, Peak mem 27.583 GB
Iter 2080: Train loss 0.042, Learning Rate 7.113e-06, It/sec 0.339, Tokens/sec 2.982, Trained Tokens 19484, Peak mem 27.583 GB
Iter 2090: Train loss 0.073, Learning Rate 7.090e-06, It/sec 0.348, Tokens/sec 3.202, Trained Tokens 19576, Peak mem 27.583 GB
Iter 2100: Train loss 0.118, Learning Rate 7.068e-06, It/sec 0.345, Tokens/sec 3.381, Trained Tokens 19674, Peak mem 27.583 GB
Iter 2110: Train loss 0.055, Learning Rate 7.045e-06, It/sec 0.333, Tokens/sec 3.060, Trained Tokens 19766, Peak mem 27.583 GB

Calculating loss...: 100%|██████████| 32/32 [00:19<00:00,  1.60it/s]

Iter 2120: Val loss 0.064, Val took 19.991s
Iter 2120: Train loss 0.085, Learning Rate 7.000e-06, It/sec 0.359, Tokens/sec 3.233, Trained Tokens 19856, Peak mem 27.583 GB
Iter 2130: Train loss 0.102, Learning Rate 6.977e-06, It/sec 0.350, Tokens/sec 3.146, Trained Tokens 19946, Peak mem 27.583 GB
Iter 2140: Train loss 0.025, Learning Rate 6.954e-06, It/sec 0.332, Tokens/sec 3.323, Trained Tokens 20046, Peak mem 27.583 GB
Iter 2150: Train loss 0.039, Learning Rate 6.931e-06, It/sec 0.380, Tokens/sec 3.344, Trained Tokens 20134, Peak mem 27.583 GB
Iter 2160: Train loss 0.118, Learning Rate 6.885e-06, It/sec 0.287, Tokens/sec 2.813, Trained Tokens 20232, Peak mem 27.583 GB
Iter 2170: Train loss 0.060, Learning Rate 6.862e-06, It/sec 0.324, Tokens/sec 3.113, Trained Tokens 20328, Peak mem 27.583 GB
Iter 2180: Train loss 0.056, Learning Rate 6.839e-06, It/sec 0.369, Tokens/sec 3.398, Trained Tokens 20420, Peak mem 27.583 GB
Iter 2190: Train loss 0.082, Learning Rate 6.816e-06, It/sec 0.320, Tokens/sec 3.200, Trained Tokens 20520, Peak mem 27.583 GB
Iter 2200: Train loss 0.058, Learning Rate 6.769e-06, It/sec 0.347, Tokens/sec 3.056, Trained Tokens 20608, Peak mem 27.583 GB
Iter 2210: Train loss 0.117, Learning Rate 6.746e-06, It/sec 0.366, Tokens/sec 3.150, Trained Tokens 20694, Peak mem 27.583 GB
Iter 2220: Train loss 0.044, Learning Rate 6.722e-06, It/sec 0.332, Tokens/sec 3.122, Trained Tokens 20788, Peak mem 27.583 GB
Iter 2230: Train loss 0.076, Learning Rate 6.699e-06, It/sec 0.330, Tokens/sec 3.168, Trained Tokens 20884, Peak mem 27.583 GB
Iter 2240: Train loss 0.080, Learning Rate 6.652e-06, It/sec 0.336, Tokens/sec 3.359, Trained Tokens 20984, Peak mem 27.583 GB
Iter 2250: Train loss 0.087, Learning Rate 6.629e-06, It/sec 0.332, Tokens/sec 3.118, Trained Tokens 21078, Peak mem 27.583 GB
Iter 2260: Train loss 0.115, Learning Rate 6.605e-06, It/sec 0.343, Tokens/sec 3.225, Trained Tokens 21172, Peak mem 27.583 GB
Iter 2270: Train loss 0.118, Learning Rate 6.582e-06, It/sec 0.343, Tokens/sec 3.292, Trained Tokens 21268, Peak mem 27.583 GB
Iter 2280: Train loss 0.029, Learning Rate 6.535e-06, It/sec 0.347, Tokens/sec 3.194, Trained Tokens 21360, Peak mem 27.583 GB
Iter 2290: Train loss 0.051, Learning Rate 6.511e-06, It/sec 0.331, Tokens/sec 3.309, Trained Tokens 21460, Peak mem 27.583 GB
Iter 2300: Train loss 0.107, Learning Rate 6.487e-06, It/sec 0.338, Tokens/sec 3.107, Trained Tokens 21552, Peak mem 27.583 GB
Iter 2310: Train loss 0.072, Learning Rate 6.464e-06, It/sec 0.360, Tokens/sec 3.236, Trained Tokens 21642, Peak mem 27.583 GB
Iter 2320: Train loss 0.078, Learning Rate 6.416e-06, It/sec 0.315, Tokens/sec 3.468, Trained Tokens 21752, Peak mem 27.583 GB
Iter 2330: Train loss 0.092, Learning Rate 6.392e-06, It/sec 0.331, Tokens/sec 3.244, Trained Tokens 21850, Peak mem 27.583 GB
Iter 2340: Train loss 0.065, Learning Rate 6.368e-06, It/sec 0.374, Tokens/sec 3.363, Trained Tokens 21940, Peak mem 27.583 GB
Iter 2350: Train loss 0.123, Learning Rate 6.345e-06, It/sec 0.326, Tokens/sec 3.264, Trained Tokens 22040, Peak mem 27.583 GB
Iter 2360: Train loss 0.050, Learning Rate 6.297e-06, It/sec 0.352, Tokens/sec 3.310, Trained Tokens 22134, Peak mem 27.583 GB
Iter 2370: Train loss 0.084, Learning Rate 6.273e-06, It/sec 0.338, Tokens/sec 2.903, Trained Tokens 22220, Peak mem 27.583 GB
Iter 2380: Train loss 0.118, Learning Rate 6.249e-06, It/sec 0.315, Tokens/sec 2.901, Trained Tokens 22312, Peak mem 27.583 GB
Iter 2390: Train loss 0.047, Learning Rate 6.225e-06, It/sec 0.312, Tokens/sec 3.060, Trained Tokens 22410, Peak mem 27.583 GB
Iter 2400: Train loss 0.092, Learning Rate 6.177e-06, It/sec 0.333, Tokens/sec 3.129, Trained Tokens 22504, Peak mem 27.583 GB
Iter 2410: Train loss 0.057, Learning Rate 6.153e-06, It/sec 0.353, Tokens/sec 3.036, Trained Tokens 22590, Peak mem 27.583 GB
Iter 2420: Train loss 0.061, Learning Rate 6.128e-06, It/sec 0.322, Tokens/sec 3.283, Trained Tokens 22692, Peak mem 27.583 GB
Iter 2430: Train loss 0.080, Learning Rate 6.104e-06, It/sec 0.313, Tokens/sec 3.129, Trained Tokens 22792, Peak mem 27.583 GB
Iter 2440: Train loss 0.077, Learning Rate 6.056e-06, It/sec 0.364, Tokens/sec 3.420, Trained Tokens 22886, Peak mem 27.583 GB
Iter 2450: Train loss 0.096, Learning Rate 6.032e-06, It/sec 0.341, Tokens/sec 3.067, Trained Tokens 22976, Peak mem 27.583 GB
Iter 2460: Train loss 0.069, Learning Rate 6.008e-06, It/sec 0.336, Tokens/sec 3.222, Trained Tokens 23072, Peak mem 27.583 GB
Iter 2470: Train loss 0.080, Learning Rate 5.983e-06, It/sec 0.344, Tokens/sec 3.232, Trained Tokens 23166, Peak mem 27.583 GB
Iter 2480: Train loss 0.143, Learning Rate 5.935e-06, It/sec 0.349, Tokens/sec 3.350, Trained Tokens 23262, Peak mem 27.583 GB
Iter 2490: Train loss 0.038, Learning Rate 5.911e-06, It/sec 0.365, Tokens/sec 3.137, Trained Tokens 23348, Peak mem 27.583 GB
Iter 2500: Train loss 0.078, Learning Rate 5.886e-06, It/sec 0.354, Tokens/sec 3.254, Trained Tokens 23440, Peak mem 27.583 GB
Iter 2510: Train loss 0.048, Learning Rate 5.862e-06, It/sec 0.342, Tokens/sec 3.350, Trained Tokens 23538, Peak mem 27.583 GB
Iter 2520: Train loss 0.076, Learning Rate 5.813e-06, It/sec 0.344, Tokens/sec 3.237, Trained Tokens 23632, Peak mem 27.583 GB
Iter 2530: Train loss 0.025, Learning Rate 5.789e-06, It/sec 0.349, Tokens/sec 3.419, Trained Tokens 23730, Peak mem 27.583 GB
Iter 2540: Train loss 0.077, Learning Rate 5.764e-06, It/sec 0.363, Tokens/sec 3.196, Trained Tokens 23818, Peak mem 27.583 GB

Calculating loss...: 100%|██████████| 32/32 [00:18<00:00,  1.72it/s]

Iter 2544: Val loss 0.070, Val took 18.631s
Iter 2550: Train loss 0.118, Learning Rate 5.740e-06, It/sec 0.358, Tokens/sec 3.293, Trained Tokens 23910, Peak mem 27.583 GB
Iter 2560: Train loss 0.039, Learning Rate 5.691e-06, It/sec 0.354, Tokens/sec 3.332, Trained Tokens 24004, Peak mem 27.583 GB
Iter 2568: Saved adapter weights to qwen35-27b-grading-mlx-lora/adapters.safetensors and qwen35-27b-grading-mlx-lora/0002568_adapters.safetensors.
Iter 2570: Train loss 0.040, Learning Rate 5.667e-06, It/sec 0.375, Tokens/sec 3.149, Trained Tokens 24088, Peak mem 27.583 GB
Iter 2580: Train loss 0.057, Learning Rate 5.642e-06, It/sec 0.333, Tokens/sec 3.196, Trained Tokens 24184, Peak mem 27.583 GB
Iter 2590: Train loss 0.093, Learning Rate 5.618e-06, It/sec 0.364, Tokens/sec 3.206, Trained Tokens 24272, Peak mem 27.583 GB
Iter 2600: Train loss 0.052, Learning Rate 5.569e-06, It/sec 0.352, Tokens/sec 3.166, Trained Tokens 24362, Peak mem 27.583 GB
Iter 2610: Train loss 0.049, Learning Rate 5.544e-06, It/sec 0.322, Tokens/sec 3.281, Trained Tokens 24464, Peak mem 27.583 GB
Iter 2620: Train loss 0.063, Learning Rate 5.520e-06, It/sec 0.325, Tokens/sec 3.320, Trained Tokens 24566, Peak mem 27.583 GB
Iter 2630: Train loss 0.072, Learning Rate 5.495e-06, It/sec 0.348, Tokens/sec 3.064, Trained Tokens 24654, Peak mem 27.583 GB
Iter 2640: Train loss 0.044, Learning Rate 5.446e-06, It/sec 0.341, Tokens/sec 3.134, Trained Tokens 24746, Peak mem 27.583 GB
Iter 2650: Train loss 0.051, Learning Rate 5.422e-06, It/sec 0.338, Tokens/sec 3.241, Trained Tokens 24842, Peak mem 27.583 GB
Iter 2660: Train loss 0.043, Learning Rate 5.397e-06, It/sec 0.326, Tokens/sec 3.391, Trained Tokens 24946, Peak mem 27.583 GB
Iter 2670: Train loss 0.053, Learning Rate 5.373e-06, It/sec 0.333, Tokens/sec 3.193, Trained Tokens 25042, Peak mem 27.583 GB
Iter 2680: Train loss 0.065, Learning Rate 5.324e-06, It/sec 0.378, Tokens/sec 3.253, Trained Tokens 25128, Peak mem 27.583 GB
Iter 2690: Train loss 0.068, Learning Rate 5.299e-06, It/sec 0.332, Tokens/sec 3.190, Trained Tokens 25224, Peak mem 27.583 GB
Iter 2700: Train loss 0.060, Learning Rate 5.275e-06, It/sec 0.361, Tokens/sec 3.030, Trained Tokens 25308, Peak mem 27.583 GB
Iter 2710: Train loss 0.054, Learning Rate 5.250e-06, It/sec 0.371, Tokens/sec 3.340, Trained Tokens 25398, Peak mem 27.583 GB
Iter 2720: Train loss 0.045, Learning Rate 5.201e-06, It/sec 0.374, Tokens/sec 3.369, Trained Tokens 25488, Peak mem 27.583 GB
Iter 2730: Train loss 0.095, Learning Rate 5.176e-06, It/sec 0.337, Tokens/sec 3.030, Trained Tokens 25578, Peak mem 27.583 GB
Iter 2740: Train loss 0.102, Learning Rate 5.152e-06, It/sec 0.337, Tokens/sec 3.372, Trained Tokens 25678, Peak mem 27.583 GB
Iter 2750: Train loss 0.036, Learning Rate 5.127e-06, It/sec 0.364, Tokens/sec 3.274, Trained Tokens 25768, Peak mem 27.583 GB
Iter 2760: Train loss 0.036, Learning Rate 5.078e-06, It/sec 0.341, Tokens/sec 3.272, Trained Tokens 25864, Peak mem 27.583 GB
Iter 2770: Train loss 0.074, Learning Rate 5.054e-06, It/sec 0.327, Tokens/sec 3.334, Trained Tokens 25966, Peak mem 27.583 GB
Iter 2780: Train loss 0.043, Learning Rate 5.029e-06, It/sec 0.390, Tokens/sec 3.513, Trained Tokens 26056, Peak mem 27.583 GB
Iter 2790: Train loss 0.152, Learning Rate 5.005e-06, It/sec 0.318, Tokens/sec 3.303, Trained Tokens 26160, Peak mem 27.583 GB
Iter 2800: Train loss 0.066, Learning Rate 4.956e-06, It/sec 0.341, Tokens/sec 3.139, Trained Tokens 26252, Peak mem 27.583 GB
Iter 2810: Train loss 0.086, Learning Rate 4.931e-06, It/sec 0.367, Tokens/sec 3.226, Trained Tokens 26340, Peak mem 27.583 GB
Iter 2820: Train loss 0.036, Learning Rate 4.907e-06, It/sec 0.372, Tokens/sec 3.344, Trained Tokens 26430, Peak mem 27.583 GB
Iter 2830: Train loss 0.075, Learning Rate 4.882e-06, It/sec 0.347, Tokens/sec 3.196, Trained Tokens 26522, Peak mem 27.583 GB
Iter 2840: Train loss 0.085, Learning Rate 4.833e-06, It/sec 0.342, Tokens/sec 3.219, Trained Tokens 26616, Peak mem 27.583 GB
Iter 2850: Train loss 0.063, Learning Rate 4.809e-06, It/sec 0.336, Tokens/sec 3.022, Trained Tokens 26706, Peak mem 27.583 GB
Iter 2860: Train loss 0.017, Learning Rate 4.784e-06, It/sec 0.382, Tokens/sec 3.287, Trained Tokens 26792, Peak mem 27.583 GB
Iter 2870: Train loss 0.081, Learning Rate 4.760e-06, It/sec 0.355, Tokens/sec 3.263, Trained Tokens 26884, Peak mem 27.583 GB
Iter 2880: Train loss 0.056, Learning Rate 4.711e-06, It/sec 0.344, Tokens/sec 3.442, Trained Tokens 26984, Peak mem 27.583 GB
Iter 2890: Train loss 0.119, Learning Rate 4.687e-06, It/sec 0.337, Tokens/sec 3.167, Trained Tokens 27078, Peak mem 27.583 GB
Iter 2900: Train loss 0.091, Learning Rate 4.662e-06, It/sec 0.348, Tokens/sec 3.268, Trained Tokens 27172, Peak mem 27.583 GB
Iter 2910: Train loss 0.057, Learning Rate 4.638e-06, It/sec 0.377, Tokens/sec 3.165, Trained Tokens 27256, Peak mem 27.583 GB
Iter 2920: Train loss 0.053, Learning Rate 4.589e-06, It/sec 0.353, Tokens/sec 2.966, Trained Tokens 27340, Peak mem 27.583 GB
Iter 2930: Train loss 0.066, Learning Rate 4.565e-06, It/sec 0.330, Tokens/sec 3.231, Trained Tokens 27438, Peak mem 27.583 GB
Iter 2940: Train loss 0.071, Learning Rate 4.541e-06, It/sec 0.365, Tokens/sec 3.499, Trained Tokens 27534, Peak mem 27.583 GB
Iter 2950: Train loss 0.072, Learning Rate 4.517e-06, It/sec 0.335, Tokens/sec 3.014, Trained Tokens 27624, Peak mem 27.583 GB
Iter 2960: Train loss 0.048, Learning Rate 4.468e-06, It/sec 0.364, Tokens/sec 3.277, Trained Tokens 27714, Peak mem 27.583 GB

Calculating loss...: 100%|██████████| 32/32 [00:19<00:00,  1.65it/s]

Iter 2968: Val loss 0.070, Val took 19.440s
Iter 2970: Train loss 0.160, Learning Rate 4.444e-06, It/sec 0.327, Tokens/sec 3.273, Trained Tokens 27814, Peak mem 27.583 GB
Iter 2980: Train loss 0.163, Learning Rate 4.420e-06, It/sec 0.338, Tokens/sec 2.970, Trained Tokens 27902, Peak mem 27.583 GB
Iter 2990: Train loss 0.081, Learning Rate 4.396e-06, It/sec 0.311, Tokens/sec 3.050, Trained Tokens 28000, Peak mem 27.583 GB
Iter 3000: Train loss 0.086, Learning Rate 4.347e-06, It/sec 0.335, Tokens/sec 3.083, Trained Tokens 28092, Peak mem 27.583 GB
Iter 3010: Train loss 0.060, Learning Rate 4.323e-06, It/sec 0.372, Tokens/sec 3.271, Trained Tokens 28180, Peak mem 27.583 GB
Iter 3020: Train loss 0.035, Learning Rate 4.299e-06, It/sec 0.358, Tokens/sec 3.077, Trained Tokens 28266, Peak mem 27.583 GB
Iter 3030: Train loss 0.130, Learning Rate 4.275e-06, It/sec 0.337, Tokens/sec 3.300, Trained Tokens 28364, Peak mem 27.583 GB
Iter 3040: Train loss 0.027, Learning Rate 4.227e-06, It/sec 0.370, Tokens/sec 3.328, Trained Tokens 28454, Peak mem 27.583 GB
Iter 3050: Train loss 0.044, Learning Rate 4.203e-06, It/sec 0.340, Tokens/sec 3.192, Trained Tokens 28548, Peak mem 27.583 GB
Iter 3060: Train loss 0.061, Learning Rate 4.179e-06, It/sec 0.338, Tokens/sec 3.110, Trained Tokens 28640, Peak mem 27.583 GB
Iter 3070: Train loss 0.057, Learning Rate 4.155e-06, It/sec 0.343, Tokens/sec 3.228, Trained Tokens 28734, Peak mem 27.583 GB
Iter 3080: Train loss 0.033, Learning Rate 4.108e-06, It/sec 0.377, Tokens/sec 3.316, Trained Tokens 28822, Peak mem 27.583 GB
Iter 3090: Train loss 0.067, Learning Rate 4.084e-06, It/sec 0.366, Tokens/sec 3.371, Trained Tokens 28914, Peak mem 27.583 GB
Iter 3100: Train loss 0.223, Learning Rate 4.060e-06, It/sec 0.335, Tokens/sec 3.018, Trained Tokens 29004, Peak mem 27.583 GB
Iter 3110: Train loss 0.021, Learning Rate 4.036e-06, It/sec 0.335, Tokens/sec 3.014, Trained Tokens 29094, Peak mem 27.583 GB
Iter 3120: Train loss 0.102, Learning Rate 3.989e-06, It/sec 0.367, Tokens/sec 3.523, Trained Tokens 29190, Peak mem 27.583 GB
Iter 3130: Train loss 0.115, Learning Rate 3.965e-06, It/sec 0.332, Tokens/sec 3.124, Trained Tokens 29284, Peak mem 27.583 GB
Iter 3140: Train loss 0.098, Learning Rate 3.942e-06, It/sec 0.370, Tokens/sec 3.179, Trained Tokens 29370, Peak mem 27.583 GB
Iter 3150: Train loss 0.054, Learning Rate 3.918e-06, It/sec 0.302, Tokens/sec 3.078, Trained Tokens 29472, Peak mem 27.583 GB
Iter 3160: Train loss 0.107, Learning Rate 3.871e-06, It/sec 0.360, Tokens/sec 3.385, Trained Tokens 29566, Peak mem 27.583 GB
Iter 3170: Train loss 0.122, Learning Rate 3.848e-06, It/sec 0.321, Tokens/sec 3.208, Trained Tokens 29666, Peak mem 27.583 GB
Iter 3180: Train loss 0.043, Learning Rate 3.824e-06, It/sec 0.316, Tokens/sec 3.094, Trained Tokens 29764, Peak mem 27.583 GB
Iter 3190: Train loss 0.034, Learning Rate 3.801e-06, It/sec 0.358, Tokens/sec 3.080, Trained Tokens 29850, Peak mem 27.583 GB
Iter 3200: Train loss 0.052, Learning Rate 3.754e-06, It/sec 0.360, Tokens/sec 3.310, Trained Tokens 29942, Peak mem 27.583 GB
Iter 3210: Train loss 0.030, Learning Rate 3.731e-06, It/sec 0.349, Tokens/sec 3.072, Trained Tokens 30030, Peak mem 27.583 GB
Iter 3220: Train loss 0.070, Learning Rate 3.708e-06, It/sec 0.339, Tokens/sec 3.317, Trained Tokens 30128, Peak mem 27.583 GB
Iter 3230: Train loss 0.095, Learning Rate 3.684e-06, It/sec 0.362, Tokens/sec 3.551, Trained Tokens 30226, Peak mem 27.583 GB
Iter 3240: Train loss 0.026, Learning Rate 3.638e-06, It/sec 0.350, Tokens/sec 3.285, Trained Tokens 30320, Peak mem 27.583 GB
Iter 3250: Train loss 0.035, Learning Rate 3.615e-06, It/sec 0.348, Tokens/sec 3.134, Trained Tokens 30410, Peak mem 27.583 GB
Iter 3260: Train loss 0.054, Learning Rate 3.592e-06, It/sec 0.353, Tokens/sec 3.102, Trained Tokens 30498, Peak mem 27.583 GB
Iter 3270: Train loss 0.054, Learning Rate 3.569e-06, It/sec 0.335, Tokens/sec 2.951, Trained Tokens 30586, Peak mem 27.583 GB
Iter 3280: Train loss 0.038, Learning Rate 3.523e-06, It/sec 0.379, Tokens/sec 3.332, Trained Tokens 30674, Peak mem 27.583 GB
Iter 3290: Train loss 0.054, Learning Rate 3.500e-06, It/sec 0.342, Tokens/sec 3.082, Trained Tokens 30764, Peak mem 27.583 GB
Iter 3300: Train loss 0.044, Learning Rate 3.478e-06, It/sec 0.352, Tokens/sec 3.165, Trained Tokens 30854, Peak mem 27.583 GB
Iter 3310: Train loss 0.043, Learning Rate 3.455e-06, It/sec 0.348, Tokens/sec 3.131, Trained Tokens 30944, Peak mem 27.583 GB
Iter 3320: Train loss 0.061, Learning Rate 3.410e-06, It/sec 0.341, Tokens/sec 3.343, Trained Tokens 31042, Peak mem 27.583 GB
Iter 3330: Train loss 0.051, Learning Rate 3.387e-06, It/sec 0.327, Tokens/sec 3.462, Trained Tokens 31148, Peak mem 27.583 GB
Iter 3340: Train loss 0.071, Learning Rate 3.364e-06, It/sec 0.336, Tokens/sec 3.021, Trained Tokens 31238, Peak mem 27.583 GB
Iter 3350: Train loss 0.096, Learning Rate 3.342e-06, It/sec 0.303, Tokens/sec 3.212, Trained Tokens 31344, Peak mem 27.583 GB
Iter 3360: Train loss 0.069, Learning Rate 3.297e-06, It/sec 0.350, Tokens/sec 3.289, Trained Tokens 31438, Peak mem 27.583 GB
Iter 3370: Train loss 0.087, Learning Rate 3.275e-06, It/sec 0.334, Tokens/sec 3.140, Trained Tokens 31532, Peak mem 27.583 GB
Iter 3380: Train loss 0.062, Learning Rate 3.252e-06, It/sec 0.324, Tokens/sec 3.048, Trained Tokens 31626, Peak mem 27.583 GB
Iter 3390: Train loss 0.029, Learning Rate 3.230e-06, It/sec 0.368, Tokens/sec 3.461, Trained Tokens 31720, Peak mem 27.583 GB

Calculating loss...: 100%|██████████| 32/32 [00:19<00:00,  1.63it/s]

Iter 3392: Val loss 0.053, Val took 19.581s
Iter 3400: Train loss 0.068, Learning Rate 3.186e-06, It/sec 0.356, Tokens/sec 3.205, Trained Tokens 31810, Peak mem 27.583 GB
Iter 3410: Train loss 0.070, Learning Rate 3.164e-06, It/sec 0.313, Tokens/sec 3.130, Trained Tokens 31910, Peak mem 27.583 GB
Iter 3420: Train loss 0.073, Learning Rate 3.142e-06, It/sec 0.345, Tokens/sec 3.245, Trained Tokens 32004, Peak mem 27.583 GB
Iter 3424: Saved adapter weights to qwen35-27b-grading-mlx-lora/adapters.safetensors and qwen35-27b-grading-mlx-lora/0003424_adapters.safetensors.
Iter 3430: Train loss 0.085, Learning Rate 3.120e-06, It/sec 0.365, Tokens/sec 3.361, Trained Tokens 32096, Peak mem 27.583 GB
Iter 3440: Train loss 0.125, Learning Rate 3.076e-06, It/sec 0.331, Tokens/sec 3.439, Trained Tokens 32200, Peak mem 27.583 GB
Iter 3450: Train loss 0.112, Learning Rate 3.054e-06, It/sec 0.321, Tokens/sec 3.149, Trained Tokens 32298, Peak mem 27.583 GB
Iter 3460: Train loss 0.058, Learning Rate 3.033e-06, It/sec 0.344, Tokens/sec 3.167, Trained Tokens 32390, Peak mem 27.583 GB
Iter 3470: Train loss 0.067, Learning Rate 3.011e-06, It/sec 0.336, Tokens/sec 3.025, Trained Tokens 32480, Peak mem 27.583 GB
Iter 3480: Train loss 0.098, Learning Rate 2.968e-06, It/sec 0.344, Tokens/sec 3.300, Trained Tokens 32576, Peak mem 27.583 GB
Iter 3490: Train loss 0.091, Learning Rate 2.946e-06, It/sec 0.361, Tokens/sec 3.252, Trained Tokens 32666, Peak mem 27.583 GB
Iter 3500: Train loss 0.053, Learning Rate 2.925e-06, It/sec 0.362, Tokens/sec 3.255, Trained Tokens 32756, Peak mem 27.583 GB
Iter 3510: Train loss 0.118, Learning Rate 2.903e-06, It/sec 0.353, Tokens/sec 3.102, Trained Tokens 32844, Peak mem 27.583 GB
Iter 3520: Train loss 0.107, Learning Rate 2.861e-06, It/sec 0.362, Tokens/sec 3.334, Trained Tokens 32936, Peak mem 27.583 GB
Iter 3530: Train loss 0.045, Learning Rate 2.840e-06, It/sec 0.358, Tokens/sec 3.081, Trained Tokens 33022, Peak mem 27.583 GB
Iter 3540: Train loss 0.094, Learning Rate 2.819e-06, It/sec 0.366, Tokens/sec 3.223, Trained Tokens 33110, Peak mem 27.583 GB
Iter 3550: Train loss 0.076, Learning Rate 2.797e-06, It/sec 0.337, Tokens/sec 2.968, Trained Tokens 33198, Peak mem 27.583 GB
Iter 3560: Train loss 0.035, Learning Rate 2.756e-06, It/sec 0.333, Tokens/sec 3.126, Trained Tokens 33292, Peak mem 27.583 GB
Iter 3570: Train loss 0.039, Learning Rate 2.735e-06, It/sec 0.365, Tokens/sec 3.358, Trained Tokens 33384, Peak mem 27.583 GB
Iter 3580: Train loss 0.055, Learning Rate 2.714e-06, It/sec 0.355, Tokens/sec 3.620, Trained Tokens 33486, Peak mem 27.583 GB
Iter 3590: Train loss 0.041, Learning Rate 2.693e-06, It/sec 0.360, Tokens/sec 3.308, Trained Tokens 33578, Peak mem 27.583 GB
Iter 3600: Train loss 0.077, Learning Rate 2.652e-06, It/sec 0.353, Tokens/sec 3.111, Trained Tokens 33666, Peak mem 27.583 GB
Iter 3610: Train loss 0.063, Learning Rate 2.631e-06, It/sec 0.364, Tokens/sec 3.200, Trained Tokens 33754, Peak mem 27.583 GB
Iter 3620: Train loss 0.042, Learning Rate 2.611e-06, It/sec 0.327, Tokens/sec 3.404, Trained Tokens 33858, Peak mem 27.583 GB
Iter 3630: Train loss 0.142, Learning Rate 2.591e-06, It/sec 0.364, Tokens/sec 3.272, Trained Tokens 33948, Peak mem 27.583 GB
Iter 3640: Train loss 0.128, Learning Rate 2.550e-06, It/sec 0.352, Tokens/sec 3.023, Trained Tokens 34034, Peak mem 27.583 GB
Iter 3650: Train loss 0.038, Learning Rate 2.530e-06, It/sec 0.365, Tokens/sec 3.136, Trained Tokens 34120, Peak mem 27.583 GB
Iter 3660: Train loss 0.078, Learning Rate 2.510e-06, It/sec 0.327, Tokens/sec 3.207, Trained Tokens 34218, Peak mem 27.583 GB
Iter 3670: Train loss 0.087, Learning Rate 2.490e-06, It/sec 0.362, Tokens/sec 3.113, Trained Tokens 34304, Peak mem 27.583 GB
Iter 3680: Train loss 0.097, Learning Rate 2.450e-06, It/sec 0.342, Tokens/sec 3.213, Trained Tokens 34398, Peak mem 27.583 GB
Iter 3690: Train loss 0.071, Learning Rate 2.430e-06, It/sec 0.330, Tokens/sec 3.103, Trained Tokens 34492, Peak mem 27.583 GB
Iter 3700: Train loss 0.097, Learning Rate 2.411e-06, It/sec 0.278, Tokens/sec 2.556, Trained Tokens 34584, Peak mem 27.583 GB
Iter 3710: Train loss 0.055, Learning Rate 2.391e-06, It/sec 0.311, Tokens/sec 2.922, Trained Tokens 34678, Peak mem 27.583 GB
Iter 3720: Train loss 0.039, Learning Rate 2.352e-06, It/sec 0.334, Tokens/sec 3.005, Trained Tokens 34768, Peak mem 27.583 GB
Iter 3730: Train loss 0.071, Learning Rate 2.332e-06, It/sec 0.362, Tokens/sec 3.476, Trained Tokens 34864, Peak mem 27.583 GB
Iter 3740: Train loss 0.057, Learning Rate 2.313e-06, It/sec 0.322, Tokens/sec 3.091, Trained Tokens 34960, Peak mem 27.583 GB
Iter 3750: Train loss 0.070, Learning Rate 2.294e-06, It/sec 0.348, Tokens/sec 3.343, Trained Tokens 35056, Peak mem 27.583 GB
Iter 3760: Train loss 0.096, Learning Rate 2.256e-06, It/sec 0.351, Tokens/sec 3.087, Trained Tokens 35144, Peak mem 27.583 GB
Iter 3770: Train loss 0.039, Learning Rate 2.237e-06, It/sec 0.352, Tokens/sec 3.305, Trained Tokens 35238, Peak mem 27.583 GB
Iter 3780: Train loss 0.067, Learning Rate 2.218e-06, It/sec 0.361, Tokens/sec 3.323, Trained Tokens 35330, Peak mem 27.583 GB
Iter 3790: Train loss 0.099, Learning Rate 2.199e-06, It/sec 0.336, Tokens/sec 3.023, Trained Tokens 35420, Peak mem 27.583 GB
Iter 3800: Train loss 0.060, Learning Rate 2.161e-06, It/sec 0.310, Tokens/sec 2.916, Trained Tokens 35514, Peak mem 27.583 GB
Iter 3810: Train loss 0.027, Learning Rate 2.143e-06, It/sec 0.351, Tokens/sec 3.019, Trained Tokens 35600, Peak mem 27.583 GB

Calculating loss...: 100%|██████████| 32/32 [00:20<00:00,  1.59it/s]

Iter 3816: Val loss 0.051, Val took 20.140s
Iter 3820: Train loss 0.076, Learning Rate 2.124e-06, It/sec 0.345, Tokens/sec 3.382, Trained Tokens 35698, Peak mem 27.583 GB
Iter 3830: Train loss 0.096, Learning Rate 2.106e-06, It/sec 0.313, Tokens/sec 3.383, Trained Tokens 35806, Peak mem 27.583 GB
Iter 3840: Train loss 0.067, Learning Rate 2.069e-06, It/sec 0.326, Tokens/sec 3.191, Trained Tokens 35904, Peak mem 27.583 GB
Iter 3850: Train loss 0.066, Learning Rate 2.051e-06, It/sec 0.329, Tokens/sec 3.023, Trained Tokens 35996, Peak mem 27.583 GB
Iter 3860: Train loss 0.032, Learning Rate 2.033e-06, It/sec 0.342, Tokens/sec 3.213, Trained Tokens 36090, Peak mem 27.583 GB
Iter 3870: Train loss 0.036, Learning Rate 2.015e-06, It/sec 0.364, Tokens/sec 3.131, Trained Tokens 36176, Peak mem 27.583 GB
Iter 3880: Train loss 0.059, Learning Rate 1.979e-06, It/sec 0.346, Tokens/sec 3.118, Trained Tokens 36266, Peak mem 27.583 GB
Iter 3890: Train loss 0.067, Learning Rate 1.961e-06, It/sec 0.345, Tokens/sec 3.040, Trained Tokens 36354, Peak mem 27.583 GB
Iter 3900: Train loss 0.056, Learning Rate 1.944e-06, It/sec 0.351, Tokens/sec 3.509, Trained Tokens 36454, Peak mem 27.583 GB
Iter 3910: Train loss 0.085, Learning Rate 1.926e-06, It/sec 0.235, Tokens/sec 2.392, Trained Tokens 36556, Peak mem 27.583 GB
Iter 3920: Train loss 0.068, Learning Rate 1.891e-06, It/sec 0.313, Tokens/sec 3.006, Trained Tokens 36652, Peak mem 27.583 GB
Iter 3930: Train loss 0.113, Learning Rate 1.874e-06, It/sec 0.339, Tokens/sec 3.387, Trained Tokens 36752, Peak mem 27.583 GB
Iter 3940: Train loss 0.017, Learning Rate 1.857e-06, It/sec 0.351, Tokens/sec 3.160, Trained Tokens 36842, Peak mem 27.583 GB
Iter 3950: Train loss 0.094, Learning Rate 1.840e-06, It/sec 0.311, Tokens/sec 3.174, Trained Tokens 36944, Peak mem 27.583 GB
Iter 3960: Train loss 0.061, Learning Rate 1.806e-06, It/sec 0.345, Tokens/sec 3.245, Trained Tokens 37038, Peak mem 27.583 GB
Iter 3970: Train loss 0.032, Learning Rate 1.789e-06, It/sec 0.334, Tokens/sec 3.339, Trained Tokens 37138, Peak mem 27.583 GB
Iter 3980: Train loss 0.011, Learning Rate 1.772e-06, It/sec 0.354, Tokens/sec 3.330, Trained Tokens 37232, Peak mem 27.583 GB
Iter 3990: Train loss 0.048, Learning Rate 1.755e-06, It/sec 0.325, Tokens/sec 3.057, Trained Tokens 37326, Peak mem 27.583 GB
Iter 4000: Train loss 0.033, Learning Rate 1.722e-06, It/sec 0.350, Tokens/sec 3.146, Trained Tokens 37416, Peak mem 27.583 GB
Iter 4010: Train loss 0.066, Learning Rate 1.706e-06, It/sec 0.322, Tokens/sec 3.220, Trained Tokens 37516, Peak mem 27.583 GB
Iter 4020: Train loss 0.043, Learning Rate 1.690e-06, It/sec 0.353, Tokens/sec 3.246, Trained Tokens 37608, Peak mem 27.583 GB
Iter 4030: Train loss 0.101, Learning Rate 1.673e-06, It/sec 0.347, Tokens/sec 3.327, Trained Tokens 37704, Peak mem 27.583 GB
Iter 4040: Train loss 0.095, Learning Rate 1.641e-06, It/sec 0.322, Tokens/sec 3.353, Trained Tokens 37808, Peak mem 27.583 GB
Iter 4050: Train loss 0.059, Learning Rate 1.625e-06, It/sec 0.331, Tokens/sec 3.312, Trained Tokens 37908, Peak mem 27.583 GB
Iter 4060: Train loss 0.049, Learning Rate 1.610e-06, It/sec 0.321, Tokens/sec 3.214, Trained Tokens 38008, Peak mem 27.583 GB
Iter 4070: Train loss 0.059, Learning Rate 1.594e-06, It/sec 0.360, Tokens/sec 3.172, Trained Tokens 38096, Peak mem 27.583 GB
Iter 4080: Train loss 0.078, Learning Rate 1.563e-06, It/sec 0.369, Tokens/sec 3.542, Trained Tokens 38192, Peak mem 27.583 GB
Iter 4090: Train loss 0.090, Learning Rate 1.547e-06, It/sec 0.378, Tokens/sec 3.172, Trained Tokens 38276, Peak mem 27.583 GB
Iter 4100: Train loss 0.022, Learning Rate 1.532e-06, It/sec 0.354, Tokens/sec 3.182, Trained Tokens 38366, Peak mem 27.583 GB
Iter 4110: Train loss 0.067, Learning Rate 1.517e-06, It/sec 0.364, Tokens/sec 3.349, Trained Tokens 38458, Peak mem 27.583 GB
Iter 4120: Train loss 0.044, Learning Rate 1.487e-06, It/sec 0.365, Tokens/sec 3.287, Trained Tokens 38548, Peak mem 27.583 GB
Iter 4130: Train loss 0.083, Learning Rate 1.472e-06, It/sec 0.283, Tokens/sec 2.716, Trained Tokens 38644, Peak mem 27.583 GB
Iter 4140: Train loss 0.072, Learning Rate 1.457e-06, It/sec 0.344, Tokens/sec 3.370, Trained Tokens 38742, Peak mem 27.583 GB
Iter 4150: Train loss 0.044, Learning Rate 1.442e-06, It/sec 0.348, Tokens/sec 3.130, Trained Tokens 38832, Peak mem 27.583 GB
Iter 4160: Train loss 0.062, Learning Rate 1.413e-06, It/sec 0.331, Tokens/sec 3.044, Trained Tokens 38924, Peak mem 27.583 GB
Iter 4170: Train loss 0.102, Learning Rate 1.399e-06, It/sec 0.342, Tokens/sec 3.007, Trained Tokens 39012, Peak mem 27.583 GB
Iter 4180: Train loss 0.063, Learning Rate 1.384e-06, It/sec 0.329, Tokens/sec 3.162, Trained Tokens 39108, Peak mem 27.583 GB
Iter 4190: Train loss 0.100, Learning Rate 1.370e-06, It/sec 0.319, Tokens/sec 3.059, Trained Tokens 39204, Peak mem 27.583 GB
Iter 4200: Train loss 0.114, Learning Rate 1.342e-06, It/sec 0.323, Tokens/sec 3.426, Trained Tokens 39310, Peak mem 27.583 GB
Iter 4210: Train loss 0.050, Learning Rate 1.328e-06, It/sec 0.325, Tokens/sec 3.316, Trained Tokens 39412, Peak mem 27.583 GB
Iter 4220: Train loss 0.108, Learning Rate 1.314e-06, It/sec 0.320, Tokens/sec 3.200, Trained Tokens 39512, Peak mem 27.583 GB
Iter 4230: Train loss 0.073, Learning Rate 1.301e-06, It/sec 0.328, Tokens/sec 3.146, Trained Tokens 39608, Peak mem 27.583 GB

Calculating loss...: 100%|██████████| 32/32 [00:19<00:00,  1.66it/s]

Iter 4240: Val loss 0.064, Val took 19.247s
Iter 4240: Train loss 0.126, Learning Rate 1.273e-06, It/sec 0.327, Tokens/sec 3.075, Trained Tokens 39702, Peak mem 27.583 GB
Iter 4250: Train loss 0.062, Learning Rate 1.260e-06, It/sec 0.333, Tokens/sec 2.996, Trained Tokens 39792, Peak mem 27.583 GB
Iter 4260: Train loss 0.083, Learning Rate 1.247e-06, It/sec 0.352, Tokens/sec 3.309, Trained Tokens 39886, Peak mem 27.583 GB
Iter 4270: Train loss 0.023, Learning Rate 1.234e-06, It/sec 0.362, Tokens/sec 2.970, Trained Tokens 39968, Peak mem 27.583 GB
Iter 4280: Train loss 0.045, Learning Rate 1.208e-06, It/sec 0.330, Tokens/sec 3.101, Trained Tokens 40062, Peak mem 27.583 GB
Iter 4280: Saved adapter weights to qwen35-27b-grading-mlx-lora/adapters.safetensors and qwen35-27b-grading-mlx-lora/0004280_adapters.safetensors.
Iter 4290: Train loss 0.037, Learning Rate 1.195e-06, It/sec 0.320, Tokens/sec 2.684, Trained Tokens 40146, Peak mem 27.583 GB
Iter 4300: Train loss 0.069, Learning Rate 1.182e-06, It/sec 0.349, Tokens/sec 3.494, Trained Tokens 40246, Peak mem 27.583 GB
Iter 4310: Train loss 0.082, Learning Rate 1.169e-06, It/sec 0.337, Tokens/sec 3.303, Trained Tokens 40344, Peak mem 27.583 GB
Iter 4320: Train loss 0.083, Learning Rate 1.145e-06, It/sec 0.337, Tokens/sec 3.165, Trained Tokens 40438, Peak mem 27.583 GB
Iter 4330: Train loss 0.090, Learning Rate 1.132e-06, It/sec 0.341, Tokens/sec 3.004, Trained Tokens 40526, Peak mem 27.583 GB
Iter 4340: Train loss 0.043, Learning Rate 1.120e-06, It/sec 0.337, Tokens/sec 3.031, Trained Tokens 40616, Peak mem 27.583 GB
Iter 4350: Train loss 0.065, Learning Rate 1.108e-06, It/sec 0.345, Tokens/sec 3.035, Trained Tokens 40704, Peak mem 27.583 GB
Iter 4360: Train loss 0.027, Learning Rate 1.084e-06, It/sec 0.358, Tokens/sec 3.293, Trained Tokens 40796, Peak mem 27.583 GB
Iter 4370: Train loss 0.044, Learning Rate 1.072e-06, It/sec 0.358, Tokens/sec 2.939, Trained Tokens 40878, Peak mem 27.583 GB
Iter 4380: Train loss 0.059, Learning Rate 1.061e-06, It/sec 0.347, Tokens/sec 3.121, Trained Tokens 40968, Peak mem 27.583 GB
Iter 4390: Train loss 0.056, Learning Rate 1.049e-06, It/sec 0.340, Tokens/sec 3.193, Trained Tokens 41062, Peak mem 27.583 GB
Iter 4400: Train loss 0.072, Learning Rate 1.027e-06, It/sec 0.315, Tokens/sec 3.020, Trained Tokens 41158, Peak mem 27.583 GB
Iter 4410: Train loss 0.016, Learning Rate 1.015e-06, It/sec 0.356, Tokens/sec 3.419, Trained Tokens 41254, Peak mem 27.583 GB
Iter 4420: Train loss 0.041, Learning Rate 1.004e-06, It/sec 0.354, Tokens/sec 3.182, Trained Tokens 41344, Peak mem 27.583 GB
Iter 4430: Train loss 0.024, Learning Rate 9.935e-07, It/sec 0.333, Tokens/sec 3.132, Trained Tokens 41438, Peak mem 27.583 GB
Iter 4440: Train loss 0.090, Learning Rate 9.719e-07, It/sec 0.372, Tokens/sec 3.277, Trained Tokens 41526, Peak mem 27.583 GB
Iter 4450: Train loss 0.071, Learning Rate 9.613e-07, It/sec 0.320, Tokens/sec 3.327, Trained Tokens 41630, Peak mem 27.583 GB
Iter 4460: Train loss 0.082, Learning Rate 9.508e-07, It/sec 0.341, Tokens/sec 3.068, Trained Tokens 41720, Peak mem 27.583 GB
Iter 4470: Train loss 0.086, Learning Rate 9.404e-07, It/sec 0.331, Tokens/sec 2.980, Trained Tokens 41810, Peak mem 27.583 GB
Iter 4480: Train loss 0.062, Learning Rate 9.200e-07, It/sec 0.325, Tokens/sec 3.121, Trained Tokens 41906, Peak mem 27.583 GB
Iter 4490: Train loss 0.074, Learning Rate 9.100e-07, It/sec 0.355, Tokens/sec 3.057, Trained Tokens 41992, Peak mem 27.583 GB
Iter 4500: Train loss 0.076, Learning Rate 9.001e-07, It/sec 0.330, Tokens/sec 3.039, Trained Tokens 42084, Peak mem 27.583 GB
Iter 4510: Train loss 0.041, Learning Rate 8.903e-07, It/sec 0.354, Tokens/sec 2.975, Trained Tokens 42168, Peak mem 27.583 GB
Iter 4520: Train loss 0.065, Learning Rate 8.710e-07, It/sec 0.346, Tokens/sec 2.980, Trained Tokens 42254, Peak mem 27.583 GB
Iter 4530: Train loss 0.099, Learning Rate 8.616e-07, It/sec 0.337, Tokens/sec 3.032, Trained Tokens 42344, Peak mem 27.583 GB
Iter 4540: Train loss 0.189, Learning Rate 8.522e-07, It/sec 0.343, Tokens/sec 3.088, Trained Tokens 42434, Peak mem 27.583 GB
Iter 4550: Train loss 0.087, Learning Rate 8.430e-07, It/sec 0.347, Tokens/sec 3.262, Trained Tokens 42528, Peak mem 27.583 GB
Iter 4560: Train loss 0.076, Learning Rate 8.249e-07, It/sec 0.341, Tokens/sec 3.272, Trained Tokens 42624, Peak mem 27.583 GB
Iter 4570: Train loss 0.112, Learning Rate 8.161e-07, It/sec 0.306, Tokens/sec 3.064, Trained Tokens 42724, Peak mem 27.583 GB
Iter 4580: Train loss 0.088, Learning Rate 8.073e-07, It/sec 0.362, Tokens/sec 3.331, Trained Tokens 42816, Peak mem 27.583 GB
Iter 4590: Train loss 0.115, Learning Rate 7.987e-07, It/sec 0.313, Tokens/sec 2.875, Trained Tokens 42908, Peak mem 27.583 GB
Iter 4600: Train loss 0.124, Learning Rate 7.818e-07, It/sec 0.331, Tokens/sec 3.107, Trained Tokens 43002, Peak mem 27.583 GB
Iter 4610: Train loss 0.052, Learning Rate 7.735e-07, It/sec 0.335, Tokens/sec 3.013, Trained Tokens 43092, Peak mem 27.583 GB
Iter 4620: Train loss 0.044, Learning Rate 7.654e-07, It/sec 0.358, Tokens/sec 3.219, Trained Tokens 43182, Peak mem 27.583 GB
Iter 4630: Train loss 0.068, Learning Rate 7.574e-07, It/sec 0.341, Tokens/sec 3.134, Trained Tokens 43274, Peak mem 27.583 GB
Iter 4640: Train loss 0.060, Learning Rate 7.417e-07, It/sec 0.340, Tokens/sec 3.063, Trained Tokens 43364, Peak mem 27.583 GB
Iter 4650: Train loss 0.077, Learning Rate 7.340e-07, It/sec 0.331, Tokens/sec 3.246, Trained Tokens 43462, Peak mem 27.583 GB
Iter 4660: Train loss 0.063, Learning Rate 7.265e-07, It/sec 0.339, Tokens/sec 2.980, Trained Tokens 43550, Peak mem 27.583 GB

Calculating loss...: 100%|██████████| 32/32 [00:20<00:00,  1.60it/s]

Iter 4664: Val loss 0.067, Val took 20.026s
Iter 4670: Train loss 0.071, Learning Rate 7.190e-07, It/sec 0.327, Tokens/sec 3.267, Trained Tokens 43650, Peak mem 27.583 GB
Iter 4680: Train loss 0.060, Learning Rate 7.045e-07, It/sec 0.326, Tokens/sec 3.324, Trained Tokens 43752, Peak mem 27.583 GB
Iter 4690: Train loss 0.094, Learning Rate 6.975e-07, It/sec 0.335, Tokens/sec 3.152, Trained Tokens 43846, Peak mem 27.583 GB
Iter 4700: Train loss 0.117, Learning Rate 6.905e-07, It/sec 0.339, Tokens/sec 2.981, Trained Tokens 43934, Peak mem 27.583 GB
Iter 4710: Train loss 0.031, Learning Rate 6.837e-07, It/sec 0.357, Tokens/sec 3.144, Trained Tokens 44022, Peak mem 27.583 GB
Iter 4720: Train loss 0.104, Learning Rate 6.704e-07, It/sec 0.342, Tokens/sec 3.282, Trained Tokens 44118, Peak mem 27.583 GB
Iter 4730: Train loss 0.096, Learning Rate 6.640e-07, It/sec 0.310, Tokens/sec 3.221, Trained Tokens 44222, Peak mem 27.583 GB
Iter 4740: Train loss 0.036, Learning Rate 6.576e-07, It/sec 0.329, Tokens/sec 3.163, Trained Tokens 44318, Peak mem 27.583 GB
Iter 4750: Train loss 0.104, Learning Rate 6.514e-07, It/sec 0.280, Tokens/sec 2.968, Trained Tokens 44424, Peak mem 27.583 GB
Iter 4760: Train loss 0.077, Learning Rate 6.394e-07, It/sec 0.338, Tokens/sec 3.376, Trained Tokens 44524, Peak mem 27.583 GB
Iter 4770: Train loss 0.063, Learning Rate 6.335e-07, It/sec 0.330, Tokens/sec 3.035, Trained Tokens 44616, Peak mem 27.583 GB
Iter 4780: Train loss 0.087, Learning Rate 6.278e-07, It/sec 0.310, Tokens/sec 3.414, Trained Tokens 44726, Peak mem 27.583 GB
Iter 4790: Train loss 0.037, Learning Rate 6.222e-07, It/sec 0.359, Tokens/sec 3.303, Trained Tokens 44818, Peak mem 27.583 GB
Iter 4800: Train loss 0.100, Learning Rate 6.114e-07, It/sec 0.320, Tokens/sec 2.946, Trained Tokens 44910, Peak mem 27.583 GB
Iter 4810: Train loss 0.063, Learning Rate 6.062e-07, It/sec 0.354, Tokens/sec 3.254, Trained Tokens 45002, Peak mem 27.583 GB
Iter 4820: Train loss 0.062, Learning Rate 6.011e-07, It/sec 0.342, Tokens/sec 3.219, Trained Tokens 45096, Peak mem 27.583 GB
Iter 4830: Train loss 0.069, Learning Rate 5.961e-07, It/sec 0.321, Tokens/sec 3.149, Trained Tokens 45194, Peak mem 27.583 GB
Iter 4840: Train loss 0.099, Learning Rate 5.865e-07, It/sec 0.301, Tokens/sec 2.831, Trained Tokens 45288, Peak mem 27.583 GB
Iter 4850: Train loss 0.059, Learning Rate 5.819e-07, It/sec 0.334, Tokens/sec 3.003, Trained Tokens 45378, Peak mem 27.583 GB
Iter 4860: Train loss 0.102, Learning Rate 5.775e-07, It/sec 0.307, Tokens/sec 3.313, Trained Tokens 45486, Peak mem 27.583 GB
Iter 4870: Train loss 0.050, Learning Rate 5.731e-07, It/sec 0.343, Tokens/sec 3.157, Trained Tokens 45578, Peak mem 27.583 GB
Iter 4880: Train loss 0.073, Learning Rate 5.648e-07, It/sec 0.367, Tokens/sec 3.380, Trained Tokens 45670, Peak mem 27.583 GB
Iter 4890: Train loss 0.113, Learning Rate 5.608e-07, It/sec 0.315, Tokens/sec 3.084, Trained Tokens 45768, Peak mem 27.583 GB
Iter 4900: Train loss 0.037, Learning Rate 5.570e-07, It/sec 0.332, Tokens/sec 3.118, Trained Tokens 45862, Peak mem 27.583 GB
Iter 4910: Train loss 0.053, Learning Rate 5.532e-07, It/sec 0.344, Tokens/sec 3.162, Trained Tokens 45954, Peak mem 27.583 GB
Iter 4920: Train loss 0.037, Learning Rate 5.462e-07, It/sec 0.371, Tokens/sec 3.114, Trained Tokens 46038, Peak mem 27.583 GB
Iter 4930: Train loss 0.117, Learning Rate 5.428e-07, It/sec 0.302, Tokens/sec 2.961, Trained Tokens 46136, Peak mem 27.583 GB
Iter 4940: Train loss 0.082, Learning Rate 5.396e-07, It/sec 0.319, Tokens/sec 3.059, Trained Tokens 46232, Peak mem 27.583 GB
Iter 4950: Train loss 0.112, Learning Rate 5.365e-07, It/sec 0.306, Tokens/sec 3.118, Trained Tokens 46334, Peak mem 27.583 GB
Iter 4960: Train loss 0.073, Learning Rate 5.307e-07, It/sec 0.328, Tokens/sec 3.084, Trained Tokens 46428, Peak mem 27.583 GB
Iter 4970: Train loss 0.073, Learning Rate 5.279e-07, It/sec 0.342, Tokens/sec 3.077, Trained Tokens 46518, Peak mem 27.583 GB
Iter 4980: Train loss 0.048, Learning Rate 5.253e-07, It/sec 0.356, Tokens/sec 3.204, Trained Tokens 46608, Peak mem 27.583 GB
Iter 4990: Train loss 0.033, Learning Rate 5.229e-07, It/sec 0.320, Tokens/sec 3.073, Trained Tokens 46704, Peak mem 27.583 GB
Iter 5000: Train loss 0.053, Learning Rate 5.183e-07, It/sec 0.321, Tokens/sec 2.952, Trained Tokens 46796, Peak mem 27.583 GB
Iter 5010: Train loss 0.045, Learning Rate 5.162e-07, It/sec 0.330, Tokens/sec 3.299, Trained Tokens 46896, Peak mem 27.583 GB
Iter 5020: Train loss 0.054, Learning Rate 5.143e-07, It/sec 0.297, Tokens/sec 3.268, Trained Tokens 47006, Peak mem 27.583 GB
Iter 5030: Train loss 0.042, Learning Rate 5.124e-07, It/sec 0.362, Tokens/sec 3.260, Trained Tokens 47096, Peak mem 27.583 GB
Iter 5040: Train loss 0.044, Learning Rate 5.091e-07, It/sec 0.335, Tokens/sec 3.085, Trained Tokens 47188, Peak mem 27.583 GB
Iter 5050: Train loss 0.081, Learning Rate 5.077e-07, It/sec 0.335, Tokens/sec 3.082, Trained Tokens 47280, Peak mem 27.583 GB
Iter 5060: Train loss 0.056, Learning Rate 5.063e-07, It/sec 0.329, Tokens/sec 3.093, Trained Tokens 47374, Peak mem 27.583 GB
Iter 5070: Train loss 0.070, Learning Rate 5.051e-07, It/sec 0.358, Tokens/sec 2.937, Trained Tokens 47456, Peak mem 27.583 GB
Iter 5080: Train loss 0.062, Learning Rate 5.031e-07, It/sec 0.369, Tokens/sec 3.246, Trained Tokens 47544, Peak mem 27.583 GB

Calculating loss...: 100%|██████████| 32/32 [00:19<00:00,  1.66it/s]

Iter 5088: Val loss 0.059, Val took 19.281s
Iter 5090: Train loss 0.082, Learning Rate 5.023e-07, It/sec 0.335, Tokens/sec 3.418, Trained Tokens 47646, Peak mem 27.583 GB
Iter 5100: Train loss 0.119, Learning Rate 5.016e-07, It/sec 0.358, Tokens/sec 3.221, Trained Tokens 47736, Peak mem 27.583 GB
Iter 5110: Train loss 0.065, Learning Rate 5.010e-07, It/sec 0.360, Tokens/sec 3.240, Trained Tokens 47826, Peak mem 27.583 GB
Iter 5120: Train loss 0.044, Learning Rate 5.003e-07, It/sec 0.359, Tokens/sec 3.157, Trained Tokens 47914, Peak mem 27.583 GB
Iter 5130: Train loss 0.012, Learning Rate 5.001e-07, It/sec 0.370, Tokens/sec 3.333, Trained Tokens 48004, Peak mem 27.583 GB

Calculating loss...: 100%|██████████| 32/32 [00:20<00:00,  1.59it/s]

Iter 5136: Val loss 0.080, Val took 20.110s
Iter 5136: Train loss 0.043, Learning Rate 5.000e-07, It/sec 0.601, Tokens/sec 3.126, Trained Tokens 48056, Peak mem 27.583 GB
Iter 5136: Saved adapter weights to qwen35-27b-grading-mlx-lora/adapters.safetensors and qwen35-27b-grading-mlx-lora/0005136_adapters.safetensors.
Saved final weights to qwen35-27b-grading-mlx-lora/adapters.safetensors.

## 9. Load the adapter and run deterministic inference

Run this only after training has produced `adapters.safetensors`. The model and adapter are loaded once and reused.

In [10]:
from mlx_lm import generate, load
from mlx_lm.sample_utils import make_sampler

adapter_file = OUTPUT_DIR / "adapters.safetensors"
if not adapter_file.exists():
    raise FileNotFoundError(f"Train first; adapter not found at {adapter_file}")

model, mlx_tokenizer = load(MODEL_ID, adapter_path=str(OUTPUT_DIR))
greedy_sampler = make_sampler(temp=0.0)

def grading_messages(question, desired_answer, student_answer, criteria):
    criteria_text = "\n".join(f"{i + 1}. {criterion}" for i, criterion in enumerate(criteria))
    user = (
        f"Question:\n{question}\n\nDesired answer:\n{desired_answer}\n\n"
        f"Student answer:\n{student_answer}\n\nCriteria:\n{criteria_text}"
    )
    return [
        {"role": "system", "content": [{"type": "text", "text": SYSTEM_PROMPT}]},
        {"role": "user", "content": [{"type": "text", "text": user}]},
    ]

def predict_scores(question, desired_answer, student_answer, criteria):
    messages = grading_messages(question, desired_answer, student_answer, criteria)
    kwargs = {"add_generation_prompt": True}
    try:
        prompt = mlx_tokenizer.apply_chat_template(messages, enable_thinking=False, **kwargs)
    except TypeError:
        prompt = mlx_tokenizer.apply_chat_template(messages, **kwargs)
    raw = generate(
        model, mlx_tokenizer, prompt=prompt, max_tokens=max(32, len(criteria) * 6),
        sampler=greedy_sampler, verbose=False,
    ).strip()
    candidates = re.findall(r"\[\s*[01](?:\s*,\s*[01])*\s*\]", raw)
    scores = json.loads(candidates[-1]) if candidates else None
    valid = isinstance(scores, list) and len(scores) == len(criteria) and all(x in (0, 1) for x in scores)
    return {"valid": valid, "scores": scores if valid else None, "raw_output": raw}

predict_scores(
    question="Explain why HTTPS is more secure than HTTP.",
    desired_answer="HTTPS encrypts network traffic using TLS.",
    student_answer="HTTPS protects transmitted data using encryption.",
    criteria=["Mentions encryption", "Mentions TLS", "Claims HTTPS sends plaintext"],
)

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 13 files:   0%|          | 0/13 [00:00<?, ?it/s]

{'valid': True, 'scores': [1, 0, 0], 'raw_output': '[1,0,0]'}

## 10. Evaluate held-out examples

The default limit keeps evaluation practical on a laptop. Set `EVAL_LIMIT = None` for the complete test set. Invalid model responses count as incorrect for exact-match accuracy.

In [11]:
EVAL_LIMIT = 50
test_indices = split_indices["test"] if EVAL_LIMIT is None else split_indices["test"][:EVAL_LIMIT]
records = []
flat_true, flat_pred = [], []

for row_index in test_indices:
    row = df.loc[row_index]
    truth = [int(x) for x in row["criteria_score"]]
    prediction = predict_scores(
        str(row["question"]), str(row["desired_answer"]),
        str(row["student_answer"]), row["criteria"],
    )
    exact = bool(prediction["valid"] and prediction["scores"] == truth)
    if prediction["valid"]:
        flat_true.extend(truth)
        flat_pred.extend(prediction["scores"])
    records.append({
        "row_index": int(row_index), "truth": truth,
        "prediction": prediction["scores"] if prediction["valid"] else prediction["raw_output"],
        "valid": prediction["valid"], "exact_match": exact,
    })

evaluation_df = pd.DataFrame(records)
tp = sum(t == 1 and p == 1 for t, p in zip(flat_true, flat_pred))
fp = sum(t == 0 and p == 1 for t, p in zip(flat_true, flat_pred))
fn = sum(t == 1 and p == 0 for t, p in zip(flat_true, flat_pred))
precision = tp / (tp + fp) if tp + fp else 0.0
recall = tp / (tp + fn) if tp + fn else 0.0
metrics = {
    "examples": len(evaluation_df),
    "invalid_output_rate": 1 - evaluation_df["valid"].mean() if len(evaluation_df) else 0.0,
    "exact_match_accuracy": evaluation_df["exact_match"].mean() if len(evaluation_df) else 0.0,
    "per_criterion_accuracy_on_valid": sum(t == p for t, p in zip(flat_true, flat_pred)) / len(flat_true) if flat_true else 0.0,
    "precision_on_valid": precision,
    "recall_on_valid": recall,
    "f1_on_valid": 2 * precision * recall / (precision + recall) if precision + recall else 0.0,
}
display(pd.Series(metrics, name="fine_tuned_adapter"))
evaluation_df.head(20)

examples                           50.000000
invalid_output_rate                 0.000000
exact_match_accuracy                0.620000
per_criterion_accuracy_on_valid     0.780000
precision_on_valid                  0.847458
recall_on_valid                     0.793651
f1_on_valid                         0.819672
Name: fine_tuned_adapter, dtype: float64

    row_index   truth prediction  valid  exact_match
0          55  [0, 1]     [1, 1]   True        False
1          56  [0, 0]     [0, 0]   True         True
2          57  [0, 1]     [0, 1]   True         True
3          58  [1, 1]     [0, 0]   True        False
4          59  [0, 1]     [0, 1]   True         True
5          60  [0, 0]     [1, 0]   True        False
6          61  [0, 1]     [1, 1]   True        False
7          62  [1, 1]     [0, 0]   True        False
8          63  [0, 1]     [0, 1]   True         True
9          64  [1, 1]     [1, 1]   True         True
10         65  [0, 1]     [0, 1]   True         True
11         66  [0, 0]     [0, 0]   True         True
12         67  [1, 0]     [0, 0]   True        False
13         68  [0, 1]     [1, 1]   True        False
14         69  [1, 1]     [1, 1]   True         True
15         70  [0, 1]     [1, 1]   True        False
16         71  [1, 0]     [1, 0]   True         True
17         72  [1, 1]     [0, 1]   True        False
18         73  [0, 1]     [1, 1]   True        False
19         74  [0, 1]     [0, 1]   True         True

## Operational notes

- Activity Monitor's Memory Pressure is more useful than free-memory figures on macOS. Keep it green.
- A 32 GB Mac should retain the 4-layer/rank-4 profile. On 48 GB, try 8 layers before increasing rank.
- For repeatable comparisons, retain the generated JSONL split files and YAML configuration with the adapter.
- Do not fuse the adapter until evaluation is complete; keeping it separate is smaller and makes experiments easier to compare.
- The adapter is framework-specific. Export or fuse through MLX-LM if the final deployment format requires merged weights.